export const baccQuestions = [
  {
    id: 1,
    question: 'Quelle est la fonction principale des mitochondries dans une cellule ?',
    options: ['Produire de l’énergie', 'Stocker l’ADN', 'Synthétiser les protéines', 'Réguler la transpiration'],
    correctAnswer: 0,
  },
  {
    id: 2,
    question: 'Quel organe filtre le sang dans le corps humain ?',
    options: ['Le cœur', 'Le foie', 'Le rein', 'Le poumon'],
    correctAnswer: 2,
  },
  {
    id: 3,
    question: 'Dans la classification des cellules, quelle structure contient l’information génétique ?',
    options: ['Le cytoplasme', 'Le noyau', 'La membrane', 'La vacuole'],
    correctAnswer: 1,
  },
  {
    id: 4,
    question: 'Quelle est la formule chimique de l’eau ?',
    options: ['CO2', 'O2', 'H2O', 'NaCl'],
    correctAnswer: 2,
  },
  {
    id: 5,
    question: 'Quel est le plus grand planète du système solaire ?',
    options: ['Mars', 'Jupiter', 'Vénus', 'Mercure'],
    correctAnswer: 1,
  },
  {
    id: 6,
    question: 'Quelle est la planète la plus proche du Soleil ?',
    options: ['Vénus', 'Mercure', 'Mars', 'Neptune'],
    correctAnswer: 1,
  },
  {
    id: 7,
    question: 'Dans une fraction, que représente le dénominateur ?',
    options: ['Le nombre total de parts', 'Le nombre de parts prises', 'Le résultat final', 'Le quotient'],
    correctAnswer: 0,
  },
  {
    id: 8,
    question: 'Quelle est la valeur de 7 × 8 ?',
    options: ['54', '56', '58', '60'],
    correctAnswer: 1,
  },
  {
    id: 9,
    question: 'Quel est le résultat de 15 - 7 ?',
    options: ['6', '7', '8', '9'],
    correctAnswer: 2,
  },
  {
    id: 10,
    question: 'Quelle est la capitale du Sénégal ?',
    options: ['Dakar', 'Saint-Louis', 'Thiès', 'Ziguinchor'],
    correctAnswer: 0,
  },
  {
    id: 11,
    question: 'Quel continent est traversé par l’équateur ?',
    options: ['Europe', 'Asie', 'Afrique', 'Océanie'],
    correctAnswer: 2,
  },
  {
    id: 12,
    question: 'Qui a écrit “Le Petit Prince” ?',
    options: ['Victor Hugo', 'Antoine de Saint-Exupéry', 'Albert Camus', 'Molière'],
    correctAnswer: 1,
  },
  {
    id: 13,
    question: 'Quel est le synonyme de “rapidement” ?',
    options: ['Lentement', 'Vite', 'Doucement', 'Longtemps'],
    correctAnswer: 1,
  },
  {
    id: 14,
    question: 'Quel est l’antonyme de “heureux” ?',
    options: ['Satisfait', 'Content', 'Malheureux', 'Tranquille'],
    correctAnswer: 2,
  },
  {
    id: 15,
    question: 'Dans une phrase, le verbe exprime généralement ?',
    options: ['Le nom de l’objet', 'L’action ou l’état', 'Le pronom', 'La ponctuation'],
    correctAnswer: 1,
  },
  {
    id: 16,
    question: 'Quel est le terme utilisé pour une idée principale d’un texte ?',
    options: ['Conclusion', 'Thèse', 'Argument', 'Exemple'],
    correctAnswer: 1,
  },
  {
    id: 17,
    question: 'Quel pays a pour capitale Nairobi ?',
    options: ['Kenya', 'Tanzanie', 'Ouganda', 'Rwanda'],
    correctAnswer: 0,
  },
  {
    id: 18,
    question: 'Quelle est la langue officielle du Brésil ?',
    options: ['Espagnol', 'Portugais', 'Français', 'Italien'],
    correctAnswer: 1,
  },
  {
    id: 19,
    question: 'Quel instrument sert à mesurer la température ?',
    options: ['Baromètre', 'Thermomètre', 'Altimètre', 'Voltmetre'],
    correctAnswer: 1,
  },
  {
    id: 20,
    question: 'Quel est le plus grand océan du monde ?',
    options: ['Océan Atlantique', 'Océan Indien', 'Océan Arctique', 'Océan Pacifique'],
    correctAnswer: 3,
  },
  {
    id: 21,
    question: 'Quel est le nombre premier après 11 ?',
    options: ['12', '13', '14', '15'],
    correctAnswer: 1,
  },
  {
    id: 22,
    question: 'Quelle est la racine carrée de 49 ?',
    options: ['6', '7', '8', '9'],
    correctAnswer: 1,
  },
  {
    id: 23,
    question: 'Quel est le résultat de 3² ?',
    options: ['6', '7', '8', '9'],
    correctAnswer: 3,
  },
  {
    id: 24,
    question: 'Quel est l’angle d’un triangle équilatéral ?',
    options: ['60°', '90°', '120°', '180°'],
    correctAnswer: 0,
  },
  {
    id: 25,
    question: 'Quelle est la capitale du Maroc ?',
    options: ['Alger', 'Rabat', 'Tunis', 'Tripoli'],
    correctAnswer: 1,
  },
  {
    id: 26,
    question: 'Quel est le nom de la force qui attire les objets vers la Terre ?',
    options: ['Magnétisme', 'Gravité', 'Friction', 'Électricité'],
    correctAnswer: 1,
  },
  {
    id: 27,
    question: 'Quel est l’élément chimique représenté par le symbole Fe ?',
    options: ['Fer', 'Fluor', 'Félin', 'Francium'],
    correctAnswer: 0,
  },
  {
    id: 28,
    question: 'Quel type de réaction transforme un solide en liquide ?',
    options: ['Fusion', 'Vaporisation', 'Condensation', 'Solidification'],
    correctAnswer: 0,
  },
  {
    id: 29,
    question: 'Comment s’appelle la couche de l’atmosphère où nous vivons ?',
    options: ['Stratosphère', 'Mésosphère', 'Troposphère', 'Thermosphère'],
    correctAnswer: 2,
  },
  {
    id: 30,
    question: 'Quel est le premier ministre de l’Ancien Régime français ?',
    options: ['Roi', 'Président', 'Premier ministre', 'Empereur'],
    correctAnswer: 0,
  },
  {
    id: 31,
    question: 'Quelle guerre a opposé la France et l’Allemagne de 1870 à 1871 ?',
    options: ['Guerre de Cent Ans', 'Guerre franco-prussienne', 'Première Guerre mondiale', 'Seconde Guerre mondiale'],
    correctAnswer: 1,
  },
  {
    id: 32,
    question: 'Quel événement marque la fin de la Seconde Guerre mondiale en Europe ?',
    options: ['Le débarquement de Normandie', 'La bataille de Verdun', 'Le 8 mai 1945', 'La révolution française'],
    correctAnswer: 2,
  },
  {
    id: 33,
    question: 'Qui a proclamé les Droits de l’Homme et du Citoyen ?',
    options: ['Napoléon Bonaparte', 'Louis XVI', 'La Convention', 'L’Assemblée constituante'],
    correctAnswer: 3,
  },
  {
    id: 34,
    question: 'Quelle est la capitale de l’Egypte ?',
    options: ['Tunis', 'Le Caire', 'Alger', 'Rabat'],
    correctAnswer: 1,
  },
  {
    id: 35,
    question: 'Quel est le nom du document fondateur de la République française ?',
    options: ['La Déclaration des droits de l’homme', 'La Constitution de 1958', 'La Charte de 1814', 'Le Traité de Versailles'],
    correctAnswer: 0,
  },
  {
    id: 36,
    question: 'Quel est le synonyme de “sagesse” ?',
    options: ['Folie', 'Prudence', 'Agressivité', 'Lâcheté'],
    correctAnswer: 1,
  },
  {
    id: 37,
    question: 'Quel mot complète : “Il fait … aujourd’hui” ?',
    options: ['beau', 'beau', 'beaux', 'belle'],
    correctAnswer: 0,
  },
  {
    id: 38,
    question: 'Dans la phrase “Les enfants jouent dans le jardin”, quel est le sujet ?',
    options: ['Les enfants', 'jouent', 'dans le jardin', 'le jardin'],
    correctAnswer: 0,
  },
  {
    id: 39,
    question: 'Quel est l’adjectif dans : “La maison blanche” ?',
    options: ['maison', 'blanche', 'la', 'house'],
    correctAnswer: 1,
  },
  {
    id: 40,
    question: 'Quel est le contraire de “ouvrir” ?',
    options: ['fermer', 'cacher', 'mettre', 'prendre'],
    correctAnswer: 0,
  },
  {
    id: 41,
    question: 'Quel est le nom de la guerre de 1914 à 1918 ?',
    options: ['Première Guerre mondiale', 'Guerre froide', 'Guerre d’Algérie', 'Guerre de Corée'],
    correctAnswer: 0,
  },
  {
    id: 42,
    question: 'Quel est le pays voisin de la France au nord ?',
    options: ['L’Espagne', 'Le Portugal', 'La Belgique', 'L’Italie'],
    correctAnswer: 2,
  },
  {
    id: 43,
    question: 'Quel est le nom du cours d’eau qui traverse Paris ?',
    options: ['La Garonne', 'La Loire', 'La Seine', 'Le Rhône'],
    correctAnswer: 2,
  },
  {
    id: 44,
    question: 'Quel est l’élément principal du réseau électrique d’une maison ?',
    options: ['L’eau', 'Le courant', 'Le bois', 'Le gaz'],
    correctAnswer: 1,
  },
  {
    id: 45,
    question: 'Quel est le plus long fleuve du monde ?',
    options: ['Le Nil', 'L’Amazone', 'Le Mississippi', 'Le Yangtsé'],
    correctAnswer: 1,
  },
  {
    id: 46,
    question: 'Quel est le nom du processus par lequel les plantes fabriquent leur nourriture ?',
    options: ['Respiration', 'Photosynthèse', 'Digestion', 'Transpiration'],
    correctAnswer: 1,
  },
  {
    id: 47,
    question: 'Quel est le symbole chimique du sodium ?',
    options: ['S', 'Na', 'So', 'N'],
    correctAnswer: 1,
  },
  {
    id: 48,
    question: 'Quel est le résultat de 20 ÷ 4 ?',
    options: ['4', '5', '6', '7'],
    correctAnswer: 1,
  },
  {
    id: 49,
    question: 'Quel est le périmètre d’un carré de côté 5 cm ?',
    options: ['10 cm', '15 cm', '20 cm', '25 cm'],
    correctAnswer: 2,
  },
  {
    id: 50,
    question: 'Combien font 12 + 19 ?',
    options: ['29', '30', '31', '32'],
    correctAnswer: 2,
  },
  {
    id: 51,
    question: 'Quel est le plus petit nombre entier positif ?',
    options: ['0', '1', '2', '3'],
    correctAnswer: 1,
  },
  {
    id: 52,
    question: 'Combien de jours comporte une semaine ?',
    options: ['5', '6', '7', '8'],
    correctAnswer: 2,
  },
  {
    id: 53,
    question: 'Quel est le nom du grand ensemble d’étoiles qui contient notre Soleil ?',
    options: ['Planète', 'Galaxie', 'Comète', 'Astéroïde'],
    correctAnswer: 1,
  },
  {
    id: 54,
    question: 'Quel est le nom de la planète rouge ?',
    options: ['Vénus', 'Mars', 'Jupiter', 'Saturne'],
    correctAnswer: 1,
  },
  {
    id: 55,
    question: 'Quel mot est un nom commun ?',
    options: ['Paris', 'Marie', 'Livre', 'France'],
    correctAnswer: 2,
  },
  {
    id: 56,
    question: 'Quelle est la forme correcte ?',
    options: ['Je suis allé', 'Je suis allée', 'Je suis allés', 'Je suis allées'],
    correctAnswer: 0,
  },
  {
    id: 57,
    question: 'Quel est le pluriel de “cheval” ?',
    options: ['Chevaux', 'Chevals', 'Chevales', 'Cheval'],
    correctAnswer: 0,
  },
  {
    id: 58,
    question: 'Quel mot complète : “Elle a … une bonne note” ?',
    options: ['eu', 'eut', 'aura', 'avait'],
    correctAnswer: 0,
  },
  {
    id: 59,
    question: 'Quel est le nom du récit où l’on raconte une histoire imaginaire ?',
    options: ['Poème', 'Roman', 'Article', 'Lettre'],
    correctAnswer: 1,
  },
  {
    id: 60,
    question: 'Quel est le principal rôle d’un introducteur dans un exposé ?',
    options: ['Résumer la conclusion', 'Présenter le sujet', 'Corriger les erreurs', 'Faire rire'],
    correctAnswer: 1,
  },
  {
    id: 61,
    question: 'Quelle est la capitale de l’Algérie ?',
    options: ['Rabat', 'Tunis', 'Alger', 'Tripoli'],
    correctAnswer: 2,
  },
  {
    id: 62,
    question: 'Quel est le nom de la ligne imaginaire qui partage la Terre en deux hémisphères ?',
    options: ['Le méridien de Greenwich', 'L’équateur', 'Le tropique du Cancer', 'Le cercle polaire'],
    correctAnswer: 1,
  },
  {
    id: 63,
    question: 'Quel est le nom de la couche externe de la Terre ?',
    options: ['Le noyau', 'Le manteau', 'La croûte', 'La lithosphère'],
    correctAnswer: 2,
  },
  {
    id: 64,
    question: 'Quel est le principal gaz contenu dans l’air ?',
    options: ['Oxygène', 'Azote', 'Dioxyde de carbone', 'Hydrogène'],
    correctAnswer: 1,
  },
  {
    id: 65,
    question: 'Comment appelle-t-on un animal qui mange à la fois de la viande et des végétaux ?',
    options: ['Carnivore', 'Herbivore', 'Omnivore', 'Insectivore'],
    correctAnswer: 2,
  },
  {
    id: 66,
    question: 'Quel est le nom du phénomène par lequel l’eau passe de l’état liquide à gazeux ?',
    options: ['Fusion', 'Solidification', 'Vaporisation', 'Condensation'],
    correctAnswer: 2,
  },
  {
    id: 67,
    question: 'Quel est le résultat de 5 × 6 ?',
    options: ['25', '30', '35', '40'],
    correctAnswer: 1,
  },
  {
    id: 68,
    question: 'Quel est l’aire d’un rectangle de 6 cm de long et 4 cm de large ?',
    options: ['10 cm²', '20 cm²', '24 cm²', '28 cm²'],
    correctAnswer: 2,
  },
  {
    id: 69,
    question: 'Quel est le plus grand nombre parmi 58, 85, 75 et 68 ?',
    options: ['58', '68', '75', '85'],
    correctAnswer: 3,
  },
  {
    id: 70,
    question: 'Combien font 100 - 45 ?',
    options: ['45', '55', '65', '75'],
    correctAnswer: 1,
  },
  {
    id: 71,
    question: 'Quel est le nom du président de la République française depuis 2017 ?',
    options: ['Nicolas Sarkozy', 'François Hollande', 'Emmanuel Macron', 'Jacques Chirac'],
    correctAnswer: 2,
  },
  {
    id: 72,
    question: 'Quel est le mois qui suit avril ?',
    options: ['Mars', 'Mai', 'Juin', 'Juillet'],
    correctAnswer: 1,
  },
  {
    id: 73,
    question: 'Quel mot est un verbe ?',
    options: ['Maison', 'Livre', 'Courir', 'Joli'],
    correctAnswer: 2,
  },
  {
    id: 74,
    question: 'Quel est l’infinitif du verbe “mangent” ?',
    options: ['Manger', 'Mangeant', 'Mangé', 'Mangent'],
    correctAnswer: 0,
  },
  {
    id: 75,
    question: 'Quel est le bon accord : “des enfants …” ?',
    options: ['heureux', 'heureuse', 'heureuses', 'heureuxes'],
    correctAnswer: 0,
  },
  {
    id: 76,
    question: 'Quelle est la capitale du Canada ?',
    options: ['Toronto', 'Ottawa', 'Montréal', 'Vancouver'],
    correctAnswer: 1,
  },
  {
    id: 77,
    question: 'Quel est le pays connu pour le kangourou ?',
    options: ['Brésil', 'Australie', 'Argentine', 'Afrique du Sud'],
    correctAnswer: 1,
  },
  {
    id: 78,
    question: 'Quel est le nom du système de gouvernement où le peuple élit ses représentants ?',
    options: ['Monarchie', 'Dictature', 'Démocratie', 'Oligarchie'],
    correctAnswer: 2,
  },
  {
    id: 79,
    question: 'Quel est l’organe qui pompe le sang dans le corps ?',
    options: ['Le foie', 'Le cœur', 'Le poumon', 'Le cerveau'],
    correctAnswer: 1,
  },
  {
    id: 80,
    question: 'Quel est l’élément principal qui permet aux plantes de pousser ?',
    options: ['Le pétrole', 'Le soleil', 'Le sable', 'Le métal'],
    correctAnswer: 1,
  },
  {
    id: 81,
    question: 'Quel est le nom de la maladie due à un manque de vitamine C ?',
    options: ['Le scorbut', 'Le diabète', 'La rougeole', 'La grippe'],
    correctAnswer: 0,
  },
  {
    id: 82,
    question: 'Quel est le nom des parties du corps qui permettent le mouvement ?',
    options: ['Les os', 'Les dents', 'Les muscles', 'Les cheveux'],
    correctAnswer: 2,
  },
  {
    id: 83,
    question: 'Quel est le plus grand désert chaud du monde ?',
    options: ['Le Sahara', 'Le Gobi', 'Le Kalahari', 'Le Namib'],
    correctAnswer: 0,
  },
  {
    id: 84,
    question: 'Quelle est la capitale du Nigeria ?',
    options: ['Lagos', 'Abuja', 'Kano', 'Port Harcourt'],
    correctAnswer: 1,
  },
  {
    id: 85,
    question: 'Quelle est la langue officielle de la Chine ?',
    options: ['Le français', 'Le chinois mandarin', 'L’arabe', 'Le japonais'],
    correctAnswer: 1,
  },
  {
    id: 86,
    question: 'Quel est le résultat de 9 × 9 ?',
    options: ['72', '81', '90', '99'],
    correctAnswer: 1,
  },
  {
    id: 87,
    question: 'Combien font 40 + 25 ?',
    options: ['55', '60', '65', '70'],
    correctAnswer: 2,
  },
  {
    id: 88,
    question: 'Quel est le nom de la forme géométrique à trois côtés ?',
    options: ['Carré', 'Triangle', 'Rectangle', 'Cercle'],
    correctAnswer: 1,
  },
  {
    id: 89,
    question: 'Quelle est la valeur de 100 ÷ 10 ?',
    options: ['10', '100', '1', '0'],
    correctAnswer: 0,
  },
  {
    id: 90,
    question: 'Quel est le nom du document qui résume les idées principales d’un texte ?',
    options: ['Un résumé', 'Une lettre', 'Un dialogue', 'Un poème'],
    correctAnswer: 0,
  },
  {
    id: 91,
    question: 'Quelle est la capitale de l’Italie ?',
    options: ['Milan', 'Rome', 'Florence', 'Venise'],
    correctAnswer: 1,
  },
  {
    id: 92,
    question: 'Quel est le nom du système de numération utilisé dans les ordinateurs ?',
    options: ['Le système décimal', 'Le système binaire', 'Le système hexadécimal', 'Le système romain'],
    correctAnswer: 1,
  },
  {
    id: 93,
    question: 'Quelle est la couleur du sang dans les veines ?',
    options: ['Bleu', 'Rouge', 'Vert', 'Jaune'],
    correctAnswer: 1,
  },
  {
    id: 94,
    question: 'Quel est le nom de l’organe qui produit la bile ?',
    options: ['Le cœur', 'Le foie', 'Le pancréas', 'Le rein'],
    correctAnswer: 1,
  },
  {
    id: 95,
    question: 'Quel est le nom de l’appareil chargé de la respiration ?',
    options: ['Le système digestif', 'Le système nerveux', 'Le système respiratoire', 'Le système osseux'],
    correctAnswer: 2,
  },
  {
    id: 96,
    question: 'Quel est le nom d’une forme de discours qui raconte une histoire ?',
    options: ['Narration', 'Description', 'Argumentation', 'Exposition'],
    correctAnswer: 0,
  },
  {
    id: 97,
    question: 'Quelle est la capitale du Japon ?',
    options: ['Osaka', 'Kyoto', 'Tokyo', 'Sapporo'],
    correctAnswer: 2,
  },
  {
    id: 98,
    question: 'Quel est le nom de l’élément de la matière qui a pour symbole O ?',
    options: ['Or', 'Oxygène', 'Argent', 'Azote'],
    correctAnswer: 1,
  },
  {
    id: 99,
    question: 'Quel est le nom du phénomène où la lumière change de direction ?',
    options: ['Réflexion', 'Refraction', 'Diffusion', 'Absorption'],
    correctAnswer: 1,
  },
  {
    id: 100,
    question: 'Quel mot signifie “qui ne peut pas être cassé” ?',
    options: ['Fragile', 'Solide', 'Mou', 'Léger'],
    correctAnswer: 1,
  },
];
