export const baccQuestions = [
  {
    id: 1,
    question: 'Quelle est la fonction principale des globules rouges ?',
    options: ['Transporter l’oxygène', 'Combattre les infections', 'Coaguler le sang', 'Digérer les aliments'],
    correctAnswer: 0,
  },
  {
    id: 2,
    question: 'Comment appelle-t-on la zone de contact entre deux plaques tectoniques ?',
    options: ['Une dorsale', 'Une faille', 'Un cratère', 'Un bassin'],
    correctAnswer: 1,
  },
  {
    id: 3,
    question: 'Quel est le rôle principal du système nerveux ?',
    options: ['Transmettre les informations dans le corps', 'Produire des hormones', 'Filtrer le sang', 'Digérer les aliments'],
    correctAnswer: 0,
  },
  {
    id: 4,
    question: 'Sur quelle faille sismique majeure Haïti est-elle en partie située ?',
    options: ['La faille de San Andreas', 'La faille Enriquillo-Plantain Garden', 'La faille de l’Anatolie', 'La faille du Rift est-africain'],
    correctAnswer: 1,
  },
  {
    id: 5,
    question: 'Quel organite cellulaire est responsable de la photosynthèse chez les plantes ?',
    options: ['La mitochondrie', 'Le chloroplaste', 'Le noyau', 'Le ribosome'],
    correctAnswer: 1,
  },
  {
    id: 6,
    question: 'Comment appelle-t-on une roche formée par le refroidissement du magma ?',
    options: ['Roche sédimentaire', 'Roche métamorphique', 'Roche ignée (magmatique)', 'Roche calcaire'],
    correctAnswer: 2,
  },
  {
    id: 7,
    question: 'Comment appelle-t-on l’étude scientifique des êtres vivants ?',
    options: ['La géologie', 'La biologie', 'La chimie', 'La physique'],
    correctAnswer: 1,
  },
  {
    id: 8,
    question: 'Quel événement géologique majeur a frappé Haïti le 12 janvier 2010 ?',
    options: ['Une éruption volcanique', 'Un séisme (tremblement de terre)', 'Un tsunami sans séisme', 'Une éruption de geyser'],
    correctAnswer: 1,
  },
  {
    id: 9,
    question: 'Comment appelle-t-on le processus par lequel une cellule se divise en deux cellules identiques ?',
    options: ['La méiose', 'La mitose', 'La fécondation', 'La photosynthèse'],
    correctAnswer: 1,
  },
  {
    id: 10,
    question: 'Comment appelle-t-on l’étude scientifique des tremblements de terre ?',
    options: ['La météorologie', 'La sismologie', 'La volcanologie', 'La géodésie'],
    correctAnswer: 1,
  },
  {
    id: 11,
    question: 'Quel organe est responsable de la production des globules rouges ?',
    options: ['Le foie', 'La rate', 'La moelle osseuse', 'Le rein'],
    correctAnswer: 2,
  },
  {
    id: 12,
    question: 'Quelle est la couche la plus externe de la Terre ?',
    options: ['Le noyau', 'Le manteau', 'La croûte terrestre', 'L’asthénosphère'],
    correctAnswer: 2,
  },
  {
    id: 13,
    question: 'Quel est le rôle principal des enzymes dans la digestion ?',
    options: ['Stocker l’énergie', 'Accélérer les réactions chimiques', 'Transporter l’oxygène', 'Combattre les microbes'],
    correctAnswer: 1,
  },
  {
    id: 14,
    question: 'Comment appelle-t-on une roche formée par l’accumulation de sédiments ?',
    options: ['Roche ignée', 'Roche sédimentaire', 'Roche métamorphique', 'Roche volcanique'],
    correctAnswer: 1,
  },
  {
    id: 15,
    question: 'Comment appelle-t-on un organisme capable de produire sa propre nourriture à partir de la lumière ?',
    options: ['Un hétérotrophe', 'Un autotrophe', 'Un parasite', 'Un décomposeur'],
    correctAnswer: 1,
  },
  {
    id: 16,
    question: 'Quelle est la principale cause des éruptions volcaniques ?',
    options: ['La remontée de magma', 'Le vent', 'La marée', 'La pluie'],
    correctAnswer: 0,
  },
  {
    id: 17,
    question: 'Quel groupe sanguin est considéré comme donneur universel ?',
    options: ['A positif', 'AB positif', 'O négatif', 'B positif'],
    correctAnswer: 2,
  },
  {
    id: 18,
    question: 'Quelle échelle est couramment utilisée pour mesurer la magnitude d’un séisme ?',
    options: ['L’échelle de Beaufort', 'L’échelle de Richter', 'L’échelle Celsius', 'L’échelle de Mercalli uniquement'],
    correctAnswer: 1,
  },
  {
    id: 19,
    question: 'Quel est le rôle principal des stomates chez les plantes ?',
    options: ['Absorber l’eau', 'Permettre les échanges gazeux', 'Stocker les sucres', 'Produire des graines'],
    correctAnswer: 1,
  },
  {
    id: 20,
    question: 'Quelles sont les deux plaques tectoniques dont le mouvement affecte particulièrement Haïti ?',
    options: ['La plaque pacifique et la plaque africaine', 'La plaque Caraïbe et la plaque nord-américaine', 'La plaque eurasienne et la plaque indienne', 'La plaque sud-américaine et la plaque antarctique'],
    correctAnswer: 1,
  },
  {
    id: 21,
    question: 'Quel insecte est responsable de la transmission du paludisme (malaria) ?',
    options: ['La mouche tsé-tsé', 'Le moustique Anophèle', 'La punaise', 'Le moustique Aedes'],
    correctAnswer: 1,
  },
  {
    id: 22,
    question: 'Comment appelle-t-on la science qui étudie la structure interne de la Terre et les roches ?',
    options: ['La météorologie', 'La géologie', 'L’astronomie', 'L’océanographie'],
    correctAnswer: 1,
  },
  {
    id: 23,
    question: 'Comment appelle-t-on la fusion d’un gamète mâle et d’un gamète femelle ?',
    options: ['La mitose', 'La fécondation', 'La photosynthèse', 'La transpiration'],
    correctAnswer: 1,
  },
  {
    id: 24,
    question: 'Quel est le nom de la couche intermédiaire entre la croûte et le noyau de la Terre ?',
    options: ['La lithosphère', 'Le manteau', 'L’atmosphère', 'L’hydrosphère'],
    correctAnswer: 1,
  },
  {
    id: 25,
    question: 'Quel organe du corps humain produit l’insuline ?',
    options: ['Le foie', 'Le pancréas', 'Le rein', 'La rate'],
    correctAnswer: 1,
  },
  {
    id: 26,
    question: 'Comment appelle-t-on un tremblement de terre secondaire qui suit un séisme principal ?',
    options: ['Un aftershock non reconnu', 'Une réplique', 'Un précurseur', 'Une aura sismique'],
    correctAnswer: 1,
  },
  {
    id: 27,
    question: 'Quel est le nom du pigment vert qui capte la lumière dans les plantes ?',
    options: ['La mélanine', 'La chlorophylle', 'L’hémoglobine', 'La kératine'],
    correctAnswer: 1,
  },
  {
    id: 28,
    question: 'Comment appelle-t-on la transformation des roches sous l’effet de la chaleur et de la pression ?',
    options: ['L’érosion', 'Le métamorphisme', 'La sédimentation', 'La fusion totale'],
    correctAnswer: 1,
  },
  {
    id: 29,
    question: 'Quelle vitamine la peau produit-elle grâce à l’exposition au soleil ?',
    options: ['Vitamine A', 'Vitamine B12', 'Vitamine C', 'Vitamine D'],
    correctAnswer: 3,
  },
  {
    id: 30,
    question: 'Quel type de roche est le calcaire ?',
    options: ['Une roche ignée', 'Une roche sédimentaire', 'Une roche métamorphique', 'Une roche volcanique'],
    correctAnswer: 1,
  },
  {
    id: 31,
    question: 'Quel est le rôle principal du système immunitaire ?',
    options: ['Digérer les aliments', 'Défendre l’organisme contre les agents pathogènes', 'Produire de l’énergie', 'Filtrer l’air'],
    correctAnswer: 1,
  },
  {
    id: 32,
    question: 'Comment appelle-t-on l’instrument qui mesure les vibrations sismiques ?',
    options: ['Le baromètre', 'Le sismographe', 'L’altimètre', 'L’hygromètre'],
    correctAnswer: 1,
  },
  {
    id: 33,
    question: 'Comment appelle-t-on l’ensemble formé par les êtres vivants et leur environnement ?',
    options: ['Une biosphère', 'Un écosystème', 'Une population', 'Une chaîne alimentaire'],
    correctAnswer: 1,
  },
  {
    id: 34,
    question: 'Quel phénomène peut être provoqué par un séisme sous-marin ?',
    options: ['Un tsunami', 'Une aurore boréale', 'Un ouragan', 'Une éclipse'],
    correctAnswer: 0,
  },
  {
    id: 35,
    question: 'Comment appelle-t-on les micro-organismes unicellulaires responsables de nombreuses maladies infectieuses ?',
    options: ['Les virus uniquement', 'Les bactéries', 'Les champignons uniquement', 'Les protozoaires uniquement'],
    correctAnswer: 1,
  },
  {
    id: 36,
    question: 'Comment appelle-t-on le point à la surface de la Terre situé directement au-dessus du foyer d’un séisme ?',
    options: ['Le méridien', 'L’épicentre', 'Le tropique', 'Le pôle'],
    correctAnswer: 1,
  },
  {
    id: 37,
    question: 'Quel est le rôle principal des globules blancs dans l’organisme ?',
    options: ['Transporter l’oxygène', 'Défendre l’organisme contre les infections', 'Coaguler le sang', 'Produire de l’énergie'],
    correctAnswer: 1,
  },
  {
    id: 38,
    question: 'Comment appelle-t-on le point d’origine souterrain d’un séisme ?',
    options: ['L’épicentre', 'Le foyer (hypocentre)', 'La faille', 'Le cratère'],
    correctAnswer: 1,
  },
  {
    id: 39,
    question: 'Quel organe stocke la bile avant sa libération dans l’intestin ?',
    options: ['Le pancréas', 'La vésicule biliaire', 'Le rein', 'La rate'],
    correctAnswer: 1,
  },
  {
    id: 40,
    question: 'Quel est le nom d’un des principaux massifs montagneux d’Haïti ?',
    options: ['Le Massif de la Selle', 'Le Massif Central', 'Les Alpes', 'La Cordillère des Andes'],
    correctAnswer: 0,
  },
  {
    id: 41,
    question: 'Comment appelle-t-on l’ensemble des caractères héréditaires transmis par les parents ?',
    options: ['Le métabolisme', 'Le patrimoine génétique', 'Le système immunitaire', 'Le cycle cellulaire'],
    correctAnswer: 1,
  },
  {
    id: 42,
    question: 'Comment appelle-t-on le mouvement lent et continu des plaques tectoniques ?',
    options: ['La subduction uniquement', 'La tectonique des plaques', 'L’érosion', 'La sédimentation'],
    correctAnswer: 1,
  },
  {
    id: 43,
    question: 'Quel est le rôle principal des poumons ?',
    options: ['Filtrer le sang', 'Échanger l’oxygène et le dioxyde de carbone', 'Produire des hormones', 'Digérer les graisses'],
    correctAnswer: 1,
  },
  {
    id: 44,
    question: 'Quel type de roche se forme par cristallisation lente du magma en profondeur ?',
    options: ['Roche volcanique', 'Roche plutonique', 'Roche sédimentaire', 'Roche calcaire'],
    correctAnswer: 1,
  },
  {
    id: 45,
    question: 'Comment appelle-t-on la maladie causée par une carence en fer dans le sang ?',
    options: ['Le diabète', 'L’anémie', 'L’asthme', 'La rougeole'],
    correctAnswer: 1,
  },
  {
    id: 46,
    question: 'Comment appelle-t-on la science qui étudie les volcans ?',
    options: ['La sismologie', 'La volcanologie', 'La météorologie', 'La minéralogie'],
    correctAnswer: 1,
  },
  {
    id: 47,
    question: 'Quel est le nom de la cellule reproductrice mâle chez l’humain ?',
    options: ['L’ovule', 'Le spermatozoïde', 'Le zygote', 'L’embryon'],
    correctAnswer: 1,
  },
  {
    id: 48,
    question: 'Quel élément chimique est le plus abondant dans la croûte terrestre ?',
    options: ['Le fer', 'L’oxygène', 'Le carbone', 'L’azote'],
    correctAnswer: 1,
  },
  {
    id: 49,
    question: 'Comment appelle-t-on l’étude des relations entre les êtres vivants et leur milieu ?',
    options: ['La génétique', 'L’écologie', 'L’anatomie', 'La physiologie'],
    correctAnswer: 1,
  },
  {
    id: 50,
    question: 'Comment appelle-t-on la zone où un séisme se produit habituellement à la limite de deux plaques ?',
    options: ['Une dorsale océanique uniquement', 'Une zone de faille', 'Un cratère', 'Un bassin sédimentaire'],
    correctAnswer: 1,
  },
];
