export const baccQuestions = [
  {
    id: 1,
    question: 'Quelle est la fonction principale des globules rouges ?',
    options: ['Transporter l’oxygène', 'Combattre les infections', 'Coaguler le sang', 'Digérer les aliments'],
    correctAnswer: 0,
  },
  {
    id: 2,
    question: 'Quel est le rôle principal du cœur ?',
    options: ['Digérer les aliments', 'Pomper le sang dans le corps', 'Filtrer les toxines', 'Produire des hormones'],
    correctAnswer: 1,
  },
  {
    id: 3,
    question: 'Quel est le rôle principal de l’ADN dans la cellule ?',
    options: ['Produire de l’énergie', 'Porter l’information génétique', 'Digérer les nutriments', 'Filtrer les toxines'],
    correctAnswer: 1,
  },
  {
    id: 4,
    question: 'Comment appelle-t-on les vaisseaux qui transportent le sang du cœur vers les organes ?',
    options: ['Les veines', 'Les artères', 'Les capillaires uniquement', 'Les nerfs'],
    correctAnswer: 1,
  },
  {
    id: 5,
    question: 'Comment appelle-t-on la zone de contact entre deux plaques tectoniques ?',
    options: ['Une dorsale', 'Une faille', 'Un cratère', 'Un bassin'],
    correctAnswer: 1,
  },
  {
    id: 6,
    question: 'Comment appelle-t-on les vaisseaux qui ramènent le sang vers le cœur ?',
    options: ['Les artères', 'Les veines', 'Les tendons', 'Les ligaments'],
    correctAnswer: 1,
  },
  {
    id: 7,
    question: 'Comment appelle-t-on le processus de division cellulaire qui produit les cellules reproductrices ?',
    options: ['La mitose', 'La méiose', 'La fécondation', 'La mutation'],
    correctAnswer: 1,
  },
  {
    id: 8,
    question: 'Quel organe reçoit les aliments après l’œsophage et commence leur digestion chimique ?',
    options: ['L’intestin grêle', 'L’estomac', 'Le foie', 'Le pancréas'],
    correctAnswer: 1,
  },
  {
    id: 9,
    question: 'Quel est le rôle principal du système nerveux ?',
    options: ['Transmettre les informations dans le corps', 'Produire des hormones', 'Filtrer le sang', 'Digérer les aliments'],
    correctAnswer: 0,
  },
  {
    id: 10,
    question: 'Comment appelle-t-on le tube qui relie la bouche à l’estomac ?',
    options: ['La trachée', 'L’œsophage', 'Le larynx', 'Le pharynx uniquement'],
    correctAnswer: 1,
  },
  {
    id: 11,
    question: 'Quel organe filtre les toxines du sang et produit la bile ?',
    options: ['Le rein', 'Le foie', 'La rate', 'Le pancréas'],
    correctAnswer: 1,
  },
  {
    id: 12,
    question: 'Quel est le rôle principal de l’intestin grêle ?',
    options: ['Stocker les déchets', 'Absorber les nutriments', 'Filtrer le sang', 'Produire de la bile'],
    correctAnswer: 1,
  },
  {
    id: 13,
    question: 'Sur quelle faille sismique majeure Haïti est-elle en partie située ?',
    options: ['La faille de San Andreas', 'La faille Enriquillo-Plantain Garden', 'La faille de l’Anatolie', 'La faille du Rift est-africain'],
    correctAnswer: 1,
  },
  {
    id: 14,
    question: 'Comment appelle-t-on la dernière partie du système digestif où l’eau est absorbée ?',
    options: ['L’estomac', 'Le gros intestin', 'L’œsophage', 'Le foie'],
    correctAnswer: 1,
  },
  {
    id: 15,
    question: 'Comment appelle-t-on la membrane qui entoure et protège la cellule ?',
    options: ['La paroi cellulaire', 'La membrane plasmique', 'Le noyau', 'Le cytosquelette'],
    correctAnswer: 1,
  },
  {
    id: 16,
    question: 'Quel sens permet de percevoir les sons ?',
    options: ['La vue', 'L’ouïe', 'L’odorat', 'Le toucher'],
    correctAnswer: 1,
  },
  {
    id: 17,
    question: 'Quel organite cellulaire est responsable de la photosynthèse chez les plantes ?',
    options: ['La mitochondrie', 'Le chloroplaste', 'Le noyau', 'Le ribosome'],
    correctAnswer: 1,
  },
  {
    id: 18,
    question: 'Comment appelle-t-on l’organe responsable de l’odorat ?',
    options: ['La langue', 'Le nez', 'L’oreille', 'La peau'],
    correctAnswer: 1,
  },
  {
    id: 19,
    question: 'Quel est le nom de l’unité de base de tous les êtres vivants ?',
    options: ['L’atome', 'La cellule', 'La molécule', 'Le tissu'],
    correctAnswer: 1,
  },
  {
    id: 20,
    question: 'Quel est le rôle principal des papilles gustatives ?',
    options: ['Percevoir les sons', 'Percevoir le goût', 'Percevoir la lumière', 'Percevoir les odeurs'],
    correctAnswer: 1,
  },
  {
    id: 21,
    question: 'Quel est le symbole chimique de l’oxygène ?',
    options: ['Ox', 'O', 'Og', 'O2'],
    correctAnswer: 1,
  },
  {
    id: 22,
    question: 'Comment appelle-t-on la cellule reproductrice femelle chez l’humain ?',
    options: ['Le spermatozoïde', 'L’ovule', 'Le zygote', 'L’embryon'],
    correctAnswer: 1,
  },
  {
    id: 23,
    question: 'Comment appelle-t-on un animal qui se nourrit exclusivement de plantes ?',
    options: ['Un carnivore', 'Un herbivore', 'Un omnivore', 'Un décomposeur'],
    correctAnswer: 1,
  },
  {
    id: 24,
    question: 'Quel est le nom de l’organe où se développe le fœtus pendant la grossesse ?',
    options: ['L’ovaire', 'L’utérus', 'Le vagin', 'La trompe utérine'],
    correctAnswer: 1,
  },
  {
    id: 25,
    question: 'Comment appelle-t-on une roche formée par le refroidissement du magma ?',
    options: ['Roche sédimentaire', 'Roche métamorphique', 'Roche ignée (magmatique)', 'Roche calcaire'],
    correctAnswer: 2,
  },
  {
    id: 26,
    question: 'Comment appelle-t-on le processus par lequel un organisme produit des descendants ?',
    options: ['La croissance', 'La reproduction', 'La respiration', 'La digestion'],
    correctAnswer: 1,
  },
  {
    id: 27,
    question: 'Quel est le rôle principal du squelette chez l’humain ?',
    options: ['Produire des hormones', 'Soutenir le corps et protéger les organes', 'Filtrer le sang', 'Digérer les aliments'],
    correctAnswer: 1,
  },
  {
    id: 28,
    question: 'Quel type de reproduction implique un seul parent, sans fécondation ?',
    options: ['La reproduction sexuée', 'La reproduction asexuée', 'La pollinisation', 'La fécondation'],
    correctAnswer: 1,
  },
  {
    id: 29,
    question: 'Comment appelle-t-on l’étude scientifique des êtres vivants ?',
    options: ['La géologie', 'La biologie', 'La chimie', 'La physique'],
    correctAnswer: 1,
  },
  {
    id: 30,
    question: 'Quel organite cellulaire est surnommé la centrale énergétique de la cellule ?',
    options: ['Le noyau', 'La mitochondrie', 'Le ribosome', 'Le lysosome'],
    correctAnswer: 1,
  },
  {
    id: 31,
    question: 'Comment appelle-t-on le processus par lequel le corps régule sa température interne ?',
    options: ['La digestion', 'La thermorégulation', 'La respiration', 'La circulation'],
    correctAnswer: 1,
  },
  {
    id: 32,
    question: 'Comment appelle-t-on le sac contenant le matériel génétique dans une cellule eucaryote ?',
    options: ['Le cytoplasme', 'Le noyau', 'La vacuole', 'La membrane'],
    correctAnswer: 1,
  },
  {
    id: 33,
    question: 'Quel événement géologique majeur a frappé Haïti le 12 janvier 2010 ?',
    options: ['Une éruption volcanique', 'Un séisme (tremblement de terre)', 'Un tsunami sans séisme', 'Une éruption de geyser'],
    correctAnswer: 1,
  },
  {
    id: 34,
    question: 'Quel est le rôle principal des ribosomes dans la cellule ?',
    options: ['Stocker l’énergie', 'Synthétiser les protéines', 'Digérer les déchets', 'Transporter l’oxygène'],
    correctAnswer: 1,
  },
  {
    id: 35,
    question: 'Quel est le nom de la substance qui transporte l’oxygène dans les globules rouges ?',
    options: ['La mélanine', 'L’hémoglobine', 'La kératine', 'L’insuline'],
    correctAnswer: 1,
  },
  {
    id: 36,
    question: 'Comment appelle-t-on l’ensemble des organes qui travaillent ensemble pour une fonction commune ?',
    options: ['Un tissu', 'Un système (appareil)', 'Une cellule', 'Un organisme'],
    correctAnswer: 1,
  },
  {
    id: 37,
    question: 'Comment appelle-t-on le processus par lequel une cellule se divise en deux cellules identiques ?',
    options: ['La méiose', 'La mitose', 'La fécondation', 'La photosynthèse'],
    correctAnswer: 1,
  },
  {
    id: 38,
    question: 'Quel est le nom de la maladie causée par un excès de sucre dans le sang ?',
    options: ['L’anémie', 'Le diabète', 'L’asthme', 'Le scorbut'],
    correctAnswer: 1,
  },
  {
    id: 39,
    question: 'Comment appelle-t-on la partie du cerveau responsable de l’équilibre et de la coordination ?',
    options: ['Le cortex', 'Le cervelet', 'L’hippocampe', 'Le bulbe rachidien'],
    correctAnswer: 1,
  },
  {
    id: 40,
    question: 'Comment appelle-t-on la pression exercée par le sang sur les parois des artères ?',
    options: ['Le rythme cardiaque', 'La tension artérielle', 'Le débit sanguin', 'La coagulation'],
    correctAnswer: 1,
  },
  {
    id: 41,
    question: 'Comment appelle-t-on l’étude scientifique des tremblements de terre ?',
    options: ['La météorologie', 'La sismologie', 'La volcanologie', 'La géodésie'],
    correctAnswer: 1,
  },
  {
    id: 42,
    question: 'Quel est le rôle principal des plaquettes sanguines ?',
    options: ['Transporter l’oxygène', 'La coagulation du sang', 'Combattre les infections', 'Produire des hormones'],
    correctAnswer: 1,
  },
  {
    id: 43,
    question: 'Quel est le rôle principal des reins ?',
    options: ['Produire de la bile', 'Filtrer le sang et produire l’urine', 'Stocker le glucose', 'Digérer les graisses'],
    correctAnswer: 1,
  },
  {
    id: 44,
    question: 'Comment appelle-t-on un animal qui n’a pas de colonne vertébrale ?',
    options: ['Un vertébré', 'Un invertébré', 'Un mammifère', 'Un reptile'],
    correctAnswer: 1,
  },
  {
    id: 45,
    question: 'Combien d’électrons possède un atome d’hydrogène neutre ?',
    options: ['1', '2', '3', '0'],
    correctAnswer: 0,
  },
  {
    id: 46,
    question: 'Quel est le nom du groupe d’animaux qui allaitent leurs petits ?',
    options: ['Les reptiles', 'Les mammifères', 'Les amphibiens', 'Les oiseaux'],
    correctAnswer: 1,
  },
  {
    id: 47,
    question: 'Comment appelle-t-on l’ensemble des espèces vivant dans un même milieu ?',
    options: ['Un individu', 'Une communauté', 'Un organe', 'Un gène'],
    correctAnswer: 1,
  },
  {
    id: 48,
    question: 'Comment appelle-t-on les animaux dont la température corporelle varie selon le milieu ?',
    options: ['Les animaux endothermes', 'Les animaux ectothermes (à sang froid)', 'Les mammifères uniquement', 'Les oiseaux uniquement'],
    correctAnswer: 1,
  },
  {
    id: 49,
    question: 'Quel organe est responsable de la production des globules rouges ?',
    options: ['Le foie', 'La rate', 'La moelle osseuse', 'Le rein'],
    correctAnswer: 2,
  },
  {
    id: 50,
    question: 'Quel est le rôle principal des racines chez une plante ?',
    options: ['Produire des fleurs', 'Absorber l’eau et les nutriments', 'Réaliser la photosynthèse', 'Produire des graines'],
    correctAnswer: 1,
  },
  {
    id: 51,
    question: 'Quel type de cellule ne possède pas de noyau bien défini ?',
    options: ['La cellule eucaryote', 'La cellule procaryote', 'La cellule végétale', 'La cellule nerveuse'],
    correctAnswer: 1,
  },
  {
    id: 52,
    question: 'Comment appelle-t-on le transport de la sève dans une plante ?',
    options: ['La transpiration', 'La circulation de la sève', 'La pollinisation', 'La germination'],
    correctAnswer: 1,
  },
  {
    id: 53,
    question: 'Quelle est la couche la plus externe de la Terre ?',
    options: ['Le noyau', 'Le manteau', 'La croûte terrestre', 'L’asthénosphère'],
    correctAnswer: 2,
  },
  {
    id: 54,
    question: 'Quel est le nom du processus de transfert du pollen d’une fleur à une autre ?',
    options: ['La germination', 'La pollinisation', 'La photosynthèse', 'La fécondation directe'],
    correctAnswer: 1,
  },
  {
    id: 55,
    question: 'Comment appelle-t-on la transformation d’un têtard en grenouille ?',
    options: ['La mitose', 'La métamorphose', 'La fécondation', 'La photosynthèse'],
    correctAnswer: 1,
  },
  {
    id: 56,
    question: 'Comment appelle-t-on un organisme qui décompose la matière organique morte ?',
    options: ['Un producteur', 'Un décomposeur', 'Un consommateur primaire', 'Un parasite'],
    correctAnswer: 1,
  },
  {
    id: 57,
    question: 'Quel est le rôle principal des enzymes dans la digestion ?',
    options: ['Stocker l’énergie', 'Accélérer les réactions chimiques', 'Transporter l’oxygène', 'Combattre les microbes'],
    correctAnswer: 1,
  },
  {
    id: 58,
    question: 'Quel est le rôle principal des anticorps ?',
    options: ['Transporter l’oxygène', 'Neutraliser les agents pathogènes', 'Digérer les aliments', 'Produire de l’énergie'],
    correctAnswer: 1,
  },
  {
    id: 59,
    question: 'Quel est le nom de l’organe qui produit les spermatozoïdes ?',
    options: ['L’ovaire', 'Le testicule', 'L’utérus', 'La prostate uniquement'],
    correctAnswer: 1,
  },
  {
    id: 60,
    question: 'Comment appelle-t-on la maladie infectieuse virale qui affaiblit gravement le système immunitaire ?',
    options: ['La grippe', 'Le VIH/SIDA', 'La rougeole', 'Le paludisme'],
    correctAnswer: 1,
  },
  {
    id: 61,
    question: 'Comment appelle-t-on une roche formée par l’accumulation de sédiments ?',
    options: ['Roche ignée', 'Roche sédimentaire', 'Roche métamorphique', 'Roche volcanique'],
    correctAnswer: 1,
  },
  {
    id: 62,
    question: 'Quel est le nom du processus par lequel le corps transforme les aliments en énergie ?',
    options: ['La respiration', 'Le métabolisme', 'La digestion uniquement', 'La circulation'],
    correctAnswer: 1,
  },
  {
    id: 63,
    question: 'Comment appelle-t-on le processus par lequel les plantes perdent de l’eau par leurs feuilles ?',
    options: ['La photosynthèse', 'La transpiration', 'La respiration', 'La germination'],
    correctAnswer: 1,
  },
  {
    id: 64,
    question: 'Comment appelle-t-on les organismes capables de vivre dans des conditions extrêmes ?',
    options: ['Des autotrophes', 'Des extrêmophiles', 'Des parasites', 'Des décomposeurs'],
    correctAnswer: 1,
  },
  {
    id: 65,
    question: 'Comment appelle-t-on un organisme capable de produire sa propre nourriture à partir de la lumière ?',
    options: ['Un hétérotrophe', 'Un autotrophe', 'Un parasite', 'Un décomposeur'],
    correctAnswer: 1,
  },
  {
    id: 66,
    question: 'Quel est le rôle principal du pancréas dans la digestion ?',
    options: ['Stocker la bile', 'Produire des enzymes digestives', 'Filtrer le sang', 'Absorber les nutriments'],
    correctAnswer: 1,
  },
  {
    id: 67,
    question: 'Quel est le principal rôle des vaccins ?',
    options: ['Guérir immédiatement une maladie', 'Stimuler le système immunitaire contre une maladie', 'Remplacer les globules rouges', 'Filtrer le sang'],
    correctAnswer: 1,
  },
  {
    id: 68,
    question: 'Comment appelle-t-on une substance produite par une glande qui régule les fonctions du corps ?',
    options: ['Une enzyme', 'Une hormone', 'Un anticorps', 'Un neurotransmetteur uniquement'],
    correctAnswer: 1,
  },
  {
    id: 69,
    question: 'Quel est le pH de l’eau pure à température ambiante ?',
    options: ['0', '7', '14', '10'],
    correctAnswer: 1,
  },
  {
    id: 70,
    question: 'Quel est le nom de la glande qui produit des hormones régulant le métabolisme ?',
    options: ['Le pancréas', 'La thyroïde', 'La rate', 'Le foie'],
    correctAnswer: 1,
  },
  {
    id: 71,
    question: 'Comment appelle-t-on l’étude scientifique des tissus vivants ?',
    options: ['La cytologie', 'L’histologie', 'La physiologie', 'L’anatomie'],
    correctAnswer: 1,
  },
  {
    id: 72,
    question: 'Comment appelle-t-on le processus par lequel les cellules utilisent l’oxygène pour produire de l’énergie ?',
    options: ['La photosynthèse', 'La respiration cellulaire', 'La fermentation', 'La digestion'],
    correctAnswer: 1,
  },
  {
    id: 73,
    question: 'Quelle est la principale cause des éruptions volcaniques ?',
    options: ['La remontée de magma', 'Le vent', 'La marée', 'La pluie'],
    correctAnswer: 0,
  },
  {
    id: 74,
    question: 'Quel est le rôle principal de la rate ?',
    options: ['Produire de la bile', 'Filtrer le sang et stocker des globules blancs', 'Digérer les graisses', 'Produire de l’insuline'],
    correctAnswer: 1,
  },
  {
    id: 75,
    question: 'Quel est le nom du liquide qui protège et nourrit le fœtus pendant la grossesse ?',
    options: ['Le plasma', 'Le liquide amniotique', 'La lymphe', 'Le sérum'],
    correctAnswer: 1,
  },
  {
    id: 76,
    question: 'Comment appelle-t-on un groupe d’organismes de la même espèce vivant dans un même lieu ?',
    options: ['Un écosystème', 'Une population', 'Une communauté', 'Un biome'],
    correctAnswer: 1,
  },
  {
    id: 77,
    question: 'Quel groupe sanguin est considéré comme donneur universel ?',
    options: ['A positif', 'AB positif', 'O négatif', 'B positif'],
    correctAnswer: 2,
  },
  {
    id: 78,
    question: 'Quel est le nom de la séquence qui montre qui mange qui dans un écosystème ?',
    options: ['Le cycle de vie', 'La chaîne alimentaire', 'Le cycle de l’eau', 'La photosynthèse'],
    correctAnswer: 1,
  },
  {
    id: 79,
    question: 'Comment appelle-t-on un organisme qui vit aux dépens d’un autre en lui causant du tort ?',
    options: ['Un symbiote', 'Un parasite', 'Un prédateur', 'Un décomposeur'],
    correctAnswer: 1,
  },
  {
    id: 80,
    question: 'Quel est le nom du gaz que les plantes absorbent principalement pendant la photosynthèse ?',
    options: ['L’oxygène', 'Le dioxyde de carbone', 'L’azote', 'L’hydrogène'],
    correctAnswer: 1,
  },
  {
    id: 81,
    question: 'Quelle échelle est couramment utilisée pour mesurer la magnitude d’un séisme ?',
    options: ['L’échelle de Beaufort', 'L’échelle de Richter', 'L’échelle Celsius', 'L’échelle de Mercalli uniquement'],
    correctAnswer: 1,
  },
  {
    id: 82,
    question: 'Comment appelle-t-on la structure osseuse qui protège le cerveau ?',
    options: ['Le bassin', 'Le crâne', 'La cage thoracique', 'La colonne vertébrale'],
    correctAnswer: 1,
  },
  {
    id: 83,
    question: 'Quel est le nom de la structure qui relie les os entre eux dans une articulation ?',
    options: ['Le tendon', 'Le ligament', 'Le cartilage seul', 'Le muscle'],
    correctAnswer: 1,
  },
  {
    id: 84,
    question: 'Quel est le nom des os qui protègent les poumons et le cœur ?',
    options: ['Les vertèbres', 'Les côtes', 'Le fémur', 'Le bassin'],
    correctAnswer: 1,
  },
  {
    id: 85,
    question: 'Quel est le rôle principal des stomates chez les plantes ?',
    options: ['Absorber l’eau', 'Permettre les échanges gazeux', 'Stocker les sucres', 'Produire des graines'],
    correctAnswer: 1,
  },
  {
    id: 86,
    question: 'Comment appelle-t-on l’unité héréditaire portée par l’ADN qui détermine un caractère ?',
    options: ['Le chromosome uniquement', 'Le gène', 'La protéine', 'L’enzyme'],
    correctAnswer: 1,
  },
  {
    id: 87,
    question: 'Comment appelle-t-on le processus de digestion qui commence dans la bouche ?',
    options: ['La déglutition', 'La mastication', 'L’absorption', 'L’excrétion'],
    correctAnswer: 1,
  },
  {
    id: 88,
    question: 'Quel est le nom de la substance amère produite par le foie qui aide à digérer les graisses ?',
    options: ['L’insuline', 'La bile', 'La salive', 'Le suc gastrique'],
    correctAnswer: 1,
  },
  {
    id: 89,
    question: 'Quelles sont les deux plaques tectoniques dont le mouvement affecte particulièrement Haïti ?',
    options: ['La plaque pacifique et la plaque africaine', 'La plaque Caraïbe et la plaque nord-américaine', 'La plaque eurasienne et la plaque indienne', 'La plaque sud-américaine et la plaque antarctique'],
    correctAnswer: 1,
  },
  {
    id: 90,
    question: 'Comment appelle-t-on l’étude scientifique de l’hérédité et des gènes ?',
    options: ['La biologie cellulaire', 'La génétique', 'L’écologie', 'La physiologie'],
    correctAnswer: 1,
  },
  {
    id: 91,
    question: 'Quel est le rôle principal des lymphocytes, un type de globules blancs ?',
    options: ['Transporter l’oxygène', 'Produire des anticorps', 'Coaguler le sang', 'Digérer les graisses'],
    correctAnswer: 1,
  },
  {
    id: 92,
    question: 'Quel est le rôle principal de la moelle épinière ?',
    options: ['Produire des globules rouges', 'Transmettre les messages nerveux entre le cerveau et le corps', 'Filtrer le sang', 'Digérer les aliments'],
    correctAnswer: 1,
  },
  {
    id: 93,
    question: 'Comment appelle-t-on une substance qui accélère une réaction chimique sans être consommée ?',
    options: ['Un réactif', 'Un catalyseur', 'Un solvant', 'Un précipité'],
    correctAnswer: 1,
  },
  {
    id: 94,
    question: 'Comment appelle-t-on les cellules spécialisées dans la transmission de l’influx nerveux ?',
    options: ['Les globules blancs', 'Les neurones', 'Les hépatocytes', 'Les ostéocytes'],
    correctAnswer: 1,
  },
  {
    id: 95,
    question: 'Comment appelle-t-on l’organe responsable de la vision ?',
    options: ['L’oreille', 'L’œil', 'Le nez', 'La peau'],
    correctAnswer: 1,
  },
  {
    id: 96,
    question: 'Quel est le nom du liquide clair qui circule dans le système lymphatique ?',
    options: ['Le plasma', 'La lymphe', 'Le sérum', 'La salive'],
    correctAnswer: 1,
  },
  {
    id: 97,
    question: 'Quel insecte est responsable de la transmission du paludisme (malaria) ?',
    options: ['La mouche tsé-tsé', 'Le moustique Anophèle', 'La punaise', 'Le moustique Aedes'],
    correctAnswer: 1,
  },
  {
    id: 98,
    question: 'Comment appelle-t-on la capacité d’un organisme à maintenir un équilibre interne stable ?',
    options: ['Le métabolisme', 'L’homéostasie', 'La reproduction', 'La croissance'],
    correctAnswer: 1,
  },
  {
    id: 99,
    question: 'Quel est le nom du muscle qui sépare le thorax de l’abdomen et aide à la respiration ?',
    options: ['Le biceps', 'Le diaphragme', 'Le triceps', 'Le mollet'],
    correctAnswer: 1,
  },
  {
    id: 100,
    question: 'Quel est le rôle principal des cils vibratiles présents dans les voies respiratoires ?',
    options: ['Produire de l’oxygène', 'Évacuer les impuretés et le mucus', 'Réchauffer l’air', 'Filtrer le sang'],
    correctAnswer: 1,
  },
  {
    id: 101,
    question: 'Comment appelle-t-on la science qui étudie la structure interne de la Terre et les roches ?',
    options: ['La météorologie', 'La géologie', 'L’astronomie', 'L’océanographie'],
    correctAnswer: 1,
  },
  {
    id: 102,
    question: 'Comment appelle-t-on le supercontinent qui regroupait toutes les terres émergées il y a environ 300 millions d’années ?',
    options: ['La Laurasie', 'La Pangée', 'Le Gondwana uniquement', 'L’Eurasie'],
    correctAnswer: 1,
  },
  {
    id: 103,
    question: 'Comment appelle-t-on une substance qui accélère les réactions chimiques dans les cellules vivantes ?',
    options: ['Une hormone', 'Une enzyme', 'Une vitamine', 'Un minéral'],
    correctAnswer: 1,
  },
  {
    id: 104,
    question: 'Comment appelle-t-on une chaîne de montagnes sous-marine où se forme une nouvelle croûte océanique ?',
    options: ['Une fosse océanique', 'Une dorsale océanique', 'Un plateau continental', 'Un archipel'],
    correctAnswer: 1,
  },
  {
    id: 105,
    question: 'Comment appelle-t-on la fusion d’un gamète mâle et d’un gamète femelle ?',
    options: ['La mitose', 'La fécondation', 'La photosynthèse', 'La transpiration'],
    correctAnswer: 1,
  },
  {
    id: 106,
    question: 'Quel est le plus grand océan de la planète ?',
    options: ['L’océan Atlantique', 'L’océan Pacifique', 'L’océan Indien', 'L’océan Arctique'],
    correctAnswer: 1,
  },
  {
    id: 107,
    question: 'Quel est le nom du processus par lequel une graine se transforme en plante ?',
    options: ['La pollinisation', 'La germination', 'La fécondation', 'La photosynthèse'],
    correctAnswer: 1,
  },
  {
    id: 108,
    question: 'Comment appelle-t-on la fosse océanique la plus profonde connue sur Terre ?',
    options: ['La fosse du Japon', 'La fosse des Mariannes', 'La fosse de Porto Rico', 'La fosse des Aléoutiennes'],
    correctAnswer: 1,
  },
  {
    id: 109,
    question: 'Quel est le nom de la couche intermédiaire entre la croûte et le noyau de la Terre ?',
    options: ['La lithosphère', 'Le manteau', 'L’atmosphère', 'L’hydrosphère'],
    correctAnswer: 1,
  },
  {
    id: 110,
    question: 'Quel type de roche se forme par la compression de restes de plantes sur des millions d’années ?',
    options: ['Le calcaire', 'Le charbon', 'Le granite', 'Le basalte'],
    correctAnswer: 1,
  },
  {
    id: 111,
    question: 'Comment appelle-t-on l’organe qui stocke le glucose sous forme de glycogène ?',
    options: ['Le rein', 'Le foie', 'La rate', 'Le pancréas'],
    correctAnswer: 1,
  },
  {
    id: 112,
    question: 'Comment appelle-t-on la couche de sol la plus riche en matière organique ?',
    options: ['L’argile', 'L’humus', 'Le sable', 'Le gravier'],
    correctAnswer: 1,
  },
  {
    id: 113,
    question: 'Quel organe du corps humain produit l’insuline ?',
    options: ['Le foie', 'Le pancréas', 'Le rein', 'La rate'],
    correctAnswer: 1,
  },
  {
    id: 114,
    question: 'Comment appelle-t-on le phénomène climatique cyclique qui réchauffe les eaux du Pacifique ?',
    options: ['La Niña', 'El Niño', 'La mousson', 'L’ouragan'],
    correctAnswer: 1,
  },
  {
    id: 115,
    question: 'Quel est le rôle principal de la peau ?',
    options: ['Digérer les aliments', 'Protéger le corps et réguler la température', 'Filtrer le sang', 'Produire des hormones uniquement'],
    correctAnswer: 1,
  },
  {
    id: 116,
    question: 'Comment appelle-t-on une région où il pleut très peu, avec une végétation rare ?',
    options: ['Une savane', 'Un désert', 'Une forêt tropicale', 'Une toundra'],
    correctAnswer: 1,
  },
  {
    id: 117,
    question: 'Comment appelle-t-on la réaction chimique entre un acide et une base ?',
    options: ['Oxydation', 'Combustion', 'Neutralisation', 'Fermentation'],
    correctAnswer: 2,
  },
  {
    id: 118,
    question: 'Quel est le principal gaz qui compose l’atmosphère terrestre ?',
    options: ['L’oxygène', 'L’azote', 'Le dioxyde de carbone', 'L’argon'],
    correctAnswer: 1,
  },
  {
    id: 119,
    question: 'Comment appelle-t-on la science qui étudie les êtres vivants microscopiques ?',
    options: ['La botanique', 'La microbiologie', 'La zoologie', 'La génétique'],
    correctAnswer: 1,
  },
  {
    id: 120,
    question: 'Comment appelle-t-on la limite entre deux masses d’air de températures différentes ?',
    options: ['Un cyclone', 'Un front météorologique', 'Un anticyclone', 'Une dépression'],
    correctAnswer: 1,
  },
  {
    id: 121,
    question: 'Comment appelle-t-on un tremblement de terre secondaire qui suit un séisme principal ?',
    options: ['Un aftershock non reconnu', 'Une réplique', 'Un précurseur', 'Une aura sismique'],
    correctAnswer: 1,
  },
  {
    id: 122,
    question: 'Quel phénomène est principalement responsable des marées ?',
    options: ['Le vent', 'L’attraction gravitationnelle de la Lune', 'Les courants marins seuls', 'La rotation de la Terre seule'],
    correctAnswer: 1,
  },
  {
    id: 123,
    question: 'Comment appelle-t-on le phénomène d’usure et de transport des roches par le vent, l’eau ou la glace ?',
    options: ['La sédimentation', 'L’érosion', 'La cristallisation', 'La subduction'],
    correctAnswer: 1,
  },
  {
    id: 124,
    question: 'Comment appelle-t-on une montagne formée par l’accumulation de lave et de cendres ?',
    options: ['Une colline', 'Un volcan', 'Un plateau', 'Une dune'],
    correctAnswer: 1,
  },
  {
    id: 125,
    question: 'Quel est le nom du pigment vert qui capte la lumière dans les plantes ?',
    options: ['La mélanine', 'La chlorophylle', 'L’hémoglobine', 'La kératine'],
    correctAnswer: 1,
  },
  {
    id: 126,
    question: 'Quel est le nom de la roche la plus commune dans la croûte océanique ?',
    options: ['Le granite', 'Le basalte', 'Le calcaire', 'Le grès'],
    correctAnswer: 1,
  },
  {
    id: 127,
    question: 'Quel est le nom de la partie la plus interne et solide de la Terre ?',
    options: ['Le manteau', 'Le noyau interne', 'La croûte', 'L’asthénosphère'],
    correctAnswer: 1,
  },
  {
    id: 128,
    question: 'Comment appelle-t-on la science qui étudie les océans ?',
    options: ['La météorologie', 'L’océanographie', 'La glaciologie', 'La climatologie'],
    correctAnswer: 1,
  },
  {
    id: 129,
    question: 'Comment appelle-t-on la transformation des roches sous l’effet de la chaleur et de la pression ?',
    options: ['L’érosion', 'Le métamorphisme', 'La sédimentation', 'La fusion totale'],
    correctAnswer: 1,
  },
  {
    id: 130,
    question: 'Comment appelle-t-on le phénomène où le sol se liquéfie temporairement lors d’un séisme ?',
    options: ['La subsidence', 'La liquéfaction', 'L’érosion', 'La sédimentation'],
    correctAnswer: 1,
  },
  {
    id: 131,
    question: 'Comment appelle-t-on une ouverture dans la croûte terrestre par laquelle s’échappe du magma ?',
    options: ['Une faille', 'Un volcan', 'Un cratère lunaire', 'Un geyser uniquement'],
    correctAnswer: 1,
  },
  {
    id: 132,
    question: 'Comment appelle-t-on une secousse sismique qui précède le séisme principal ?',
    options: ['Une réplique', 'Un avant-choc (secousse précurseur)', 'Un tsunami', 'Une aftershock uniquement'],
    correctAnswer: 1,
  },
  {
    id: 133,
    question: 'Quelle vitamine la peau produit-elle grâce à l’exposition au soleil ?',
    options: ['Vitamine A', 'Vitamine B12', 'Vitamine C', 'Vitamine D'],
    correctAnswer: 3,
  },
  {
    id: 134,
    question: 'Quel est le nom de la capitale d’Haïti, particulièrement touchée par le séisme de 2010 ?',
    options: ['Cap-Haïtien', 'Port-au-Prince', 'Jacmel', 'Les Cayes'],
    correctAnswer: 1,
  },
  {
    id: 135,
    question: 'Quel type de roche se transforme sous l’effet de la chaleur pour devenir du marbre ?',
    options: ['Le granite', 'Le calcaire', 'Le basalte', 'Le grès'],
    correctAnswer: 1,
  },
  {
    id: 136,
    question: 'Comment appelle-t-on la couche de roche partiellement fondue juste sous la lithosphère ?',
    options: ['La croûte', 'L’asthénosphère', 'Le noyau externe', 'La mésosphère'],
    correctAnswer: 1,
  },
  {
    id: 137,
    question: 'Quel type de roche est le calcaire ?',
    options: ['Une roche ignée', 'Une roche sédimentaire', 'Une roche métamorphique', 'Une roche volcanique'],
    correctAnswer: 1,
  },
  {
    id: 138,
    question: 'Quel est le nom du minéral principal qui compose le calcaire ?',
    options: ['Le quartz', 'La calcite', 'Le mica', 'Le feldspath'],
    correctAnswer: 1,
  },
  {
    id: 139,
    question: 'Comment appelle-t-on la théorie selon laquelle les continents se déplacent lentement au fil du temps ?',
    options: ['La théorie de la relativité', 'La dérive des continents', 'La théorie du Big Bang', 'La théorie de l’évolution'],
    correctAnswer: 1,
  },
  {
    id: 140,
    question: 'Comment appelle-t-on le phénomène de formation de grottes par dissolution du calcaire ?',
    options: ['L’érosion glaciaire', 'La karstification', 'La sédimentation', 'La subduction'],
    correctAnswer: 1,
  },
  {
    id: 141,
    question: 'Quelle est la formule chimique du sel de table ?',
    options: ['NaCl', 'KCl', 'CaCO3', 'H2SO4'],
    correctAnswer: 0,
  },
  {
    id: 142,
    question: 'Quel type de roche est formé par du sable compacté sur de longues périodes ?',
    options: ['Le granite', 'Le grès', 'Le basalte', 'Le marbre'],
    correctAnswer: 1,
  },
  {
    id: 143,
    question: 'Quel est le nom du minéral le plus dur connu naturellement ?',
    options: ['Le quartz', 'Le diamant', 'Le calcaire', 'Le mica'],
    correctAnswer: 1,
  },
  {
    id: 144,
    question: 'Comment appelle-t-on le point le plus élevé d’une montagne ?',
    options: ['La base', 'Le sommet', 'Le versant', 'Le col'],
    correctAnswer: 1,
  },
  {
    id: 145,
    question: 'Quel est le rôle principal du système immunitaire ?',
    options: ['Digérer les aliments', 'Défendre l’organisme contre les agents pathogènes', 'Produire de l’énergie', 'Filtrer l’air'],
    correctAnswer: 1,
  },
  {
    id: 146,
    question: 'Quel est le nom de la plus longue chaîne de montagnes du monde, en Amérique du Sud ?',
    options: ['Les Rocheuses', 'Les Andes', 'L’Himalaya', 'Les Alpes'],
    correctAnswer: 1,
  },
  {
    id: 147,
    question: 'Comment appelle-t-on l’étude scientifique des minéraux ?',
    options: ['La pétrologie uniquement', 'La minéralogie', 'La cristallographie uniquement', 'La géochimie'],
    correctAnswer: 1,
  },
  {
    id: 148,
    question: 'Comment appelle-t-on une vaste étendue plate de terre à basse altitude ?',
    options: ['Un plateau', 'Une plaine', 'Une vallée encaissée', 'Un massif'],
    correctAnswer: 1,
  },
  {
    id: 149,
    question: 'Comment appelle-t-on l’instrument qui mesure les vibrations sismiques ?',
    options: ['Le baromètre', 'Le sismographe', 'L’altimètre', 'L’hygromètre'],
    correctAnswer: 1,
  },
  {
    id: 150,
    question: 'Quel est le nom du plus grand désert froid du monde ?',
    options: ['Le Sahara', 'L’Antarctique', 'Le Gobi', 'Le Kalahari'],
    correctAnswer: 1,
  },
  {
    id: 151,
    question: 'Quel phénomène géologique est principalement responsable de la formation des chaînes de montagnes ?',
    options: ['L’érosion éolienne', 'La collision de plaques tectoniques', 'La pluie', 'Les marées'],
    correctAnswer: 1,
  },
  {
    id: 152,
    question: 'Comment appelle-t-on la roche à partir de laquelle se forme le sol par altération ?',
    options: ['Le sédiment', 'La roche mère', 'L’humus', 'L’argile'],
    correctAnswer: 1,
  },
  {
    id: 153,
    question: 'Comment appelle-t-on l’ensemble formé par les êtres vivants et leur environnement ?',
    options: ['Une biosphère', 'Un écosystème', 'Une population', 'Une chaîne alimentaire'],
    correctAnswer: 1,
  },
  {
    id: 154,
    question: 'Comment appelle-t-on le processus de formation du sol à partir de la roche ?',
    options: ['L’érosion', 'La pédogenèse', 'La sédimentation', 'La cristallisation'],
    correctAnswer: 1,
  },
  {
    id: 155,
    question: 'Comment appelle-t-on la roche en fusion sous la surface de la Terre ?',
    options: ['La lave', 'Le magma', 'Le basalte', 'La cendre'],
    correctAnswer: 1,
  },
  {
    id: 156,
    question: 'Comment appelle-t-on un mouvement soudain de terre ou de roches le long d’une pente ?',
    options: ['Une avalanche uniquement', 'Un glissement de terrain', 'Un tsunami', 'Une inondation'],
    correctAnswer: 1,
  },
  {
    id: 157,
    question: 'Quel phénomène peut être provoqué par un séisme sous-marin ?',
    options: ['Un tsunami', 'Une aurore boréale', 'Un ouragan', 'Une éclipse'],
    correctAnswer: 0,
  },
  {
    id: 158,
    question: 'Comment appelle-t-on une formation corallienne qui protège certaines côtes ?',
    options: ['Une dune', 'Une barrière de corail', 'Un delta', 'Une lagune uniquement'],
    correctAnswer: 1,
  },
  {
    id: 159,
    question: 'Quel est le nom de la roche en fusion une fois qu’elle atteint la surface ?',
    options: ['Le magma', 'La lave', 'Le granite', 'Le sédiment'],
    correctAnswer: 1,
  },
  {
    id: 160,
    question: 'Comment appelle-t-on l’étude scientifique du climat sur de longues périodes ?',
    options: ['La météorologie', 'La climatologie', 'La sismologie', 'La géodésie'],
    correctAnswer: 1,
  },
  {
    id: 161,
    question: 'Comment appelle-t-on les micro-organismes unicellulaires responsables de nombreuses maladies infectieuses ?',
    options: ['Les virus uniquement', 'Les bactéries', 'Les champignons uniquement', 'Les protozoaires uniquement'],
    correctAnswer: 1,
  },
  {
    id: 162,
    question: 'Comment appelle-t-on le phénomène d’élévation progressive du niveau des mers ?',
    options: ['La marée haute', 'L’élévation du niveau de la mer', 'Le tsunami', 'La subsidence'],
    correctAnswer: 1,
  },
  {
    id: 163,
    question: 'Comment appelle-t-on les couches successives visibles dans les roches sédimentaires ?',
    options: ['La fracturation', 'La stratification', 'La fusion', 'L’oxydation'],
    correctAnswer: 1,
  },
  {
    id: 164,
    question: 'Comment appelle-t-on la région située entre les deux tropiques, généralement chaude toute l’année ?',
    options: ['La zone tempérée', 'La zone intertropicale', 'La zone polaire', 'La zone subarctique'],
    correctAnswer: 1,
  },
  {
    id: 165,
    question: 'Combien de protons contient un atome de carbone ?',
    options: ['4', '6', '8', '12'],
    correctAnswer: 1,
  },
  {
    id: 166,
    question: 'Quel est le nom du plus grand désert chaud du monde ?',
    options: ['Le Kalahari', 'Le Sahara', 'Le désert de Gobi', 'L’Atacama'],
    correctAnswer: 1,
  },
  {
    id: 167,
    question: 'Quel type de faille se forme lorsque deux plaques glissent horizontalement l’une contre l’autre ?',
    options: ['Une faille normale', 'Une faille transformante', 'Une faille inverse', 'Une dorsale'],
    correctAnswer: 1,
  },
  {
    id: 168,
    question: 'Comment appelle-t-on une source d’eau chaude naturelle liée à l’activité volcanique ?',
    options: ['Un lac glaciaire', 'Une source thermale', 'Une rivière souterraine', 'Un aquifère'],
    correctAnswer: 1,
  },
  {
    id: 169,
    question: 'Comment appelle-t-on le point à la surface de la Terre situé directement au-dessus du foyer d’un séisme ?',
    options: ['Le méridien', 'L’épicentre', 'Le tropique', 'Le pôle'],
    correctAnswer: 1,
  },
  {
    id: 170,
    question: 'Comment appelle-t-on une île formée par l’activité d’un volcan sous-marin qui atteint la surface ?',
    options: ['Un atoll uniquement', 'Une île volcanique', 'Une péninsule', 'Un isthme'],
    correctAnswer: 1,
  },
  {
    id: 171,
    question: 'Comment appelle-t-on la partie de la Terre composée d’eau (océans, lacs, rivières) ?',
    options: ['La lithosphère', 'L’hydrosphère', 'L’atmosphère', 'La biosphère'],
    correctAnswer: 1,
  },
  {
    id: 172,
    question: 'Quel est le nom d’un gaz volcanique dangereux souvent libéré lors d’une éruption ?',
    options: ['L’azote', 'Le dioxyde de soufre', 'L’hélium', 'L’argon'],
    correctAnswer: 1,
  },
  {
    id: 173,
    question: 'Quel est le rôle principal des globules blancs dans l’organisme ?',
    options: ['Transporter l’oxygène', 'Défendre l’organisme contre les infections', 'Coaguler le sang', 'Produire de l’énergie'],
    correctAnswer: 1,
  },
  {
    id: 174,
    question: 'Quel est le nom de la plaque tectonique qui recouvre la majeure partie de l’océan Pacifique ?',
    options: ['La plaque nord-américaine', 'La plaque Pacifique', 'La plaque eurasienne', 'La plaque africaine'],
    correctAnswer: 1,
  },
  {
    id: 175,
    question: 'Quel phénomène explique principalement la formation des geysers ?',
    options: ['L’érosion marine', 'L’activité géothermique', 'La tectonique des plaques uniquement', 'Les marées'],
    correctAnswer: 1,
  },
  {
    id: 176,
    question: 'Comment appelle-t-on la remontée d’eaux profondes et froides, riches en nutriments, vers la surface ?',
    options: ['La marée', 'La remontée d’eau (upwelling)', 'La convection atmosphérique', 'L’évaporation'],
    correctAnswer: 1,
  },
  {
    id: 177,
    question: 'Comment appelle-t-on le point d’origine souterrain d’un séisme ?',
    options: ['L’épicentre', 'Le foyer (hypocentre)', 'La faille', 'Le cratère'],
    correctAnswer: 1,
  },
  {
    id: 178,
    question: 'Quel est le principal minéral utilisé pour fabriquer le ciment ?',
    options: ['Le quartz', 'Le calcaire', 'Le mica', 'Le granite'],
    correctAnswer: 1,
  },
  {
    id: 179,
    question: 'Comment appelle-t-on un fragment de roche provenant de l’espace qui atteint la surface de la Terre ?',
    options: ['Un astéroïde en orbite', 'Une météorite', 'Une comète', 'Un satellite'],
    correctAnswer: 1,
  },
  {
    id: 180,
    question: 'Comment appelle-t-on une colline formée par l’accumulation de sable poussé par le vent ?',
    options: ['Une moraine', 'Une dune', 'Une butte rocheuse', 'Un tertre'],
    correctAnswer: 1,
  },
  {
    id: 181,
    question: 'Quel organe stocke la bile avant sa libération dans l’intestin ?',
    options: ['Le pancréas', 'La vésicule biliaire', 'Le rein', 'La rate'],
    correctAnswer: 1,
  },
  {
    id: 182,
    question: 'Comment appelle-t-on le phénomène où le vent transporte et dépose du sable ou de la poussière ?',
    options: ['L’érosion fluviale', 'L’érosion éolienne', 'L’érosion glaciaire', 'La sédimentation marine'],
    correctAnswer: 1,
  },
  {
    id: 183,
    question: 'Quel est le principal minéral qui compose le sable des plages ?',
    options: ['Le calcaire', 'Le quartz', 'Le mica', 'Le granite'],
    correctAnswer: 1,
  },
  {
    id: 184,
    question: 'Comment appelle-t-on la zone de transition entre la terre et la mer, soumise aux marées ?',
    options: ['Le plateau continental', 'Le littoral', 'L’estuaire uniquement', 'Le talus continental'],
    correctAnswer: 1,
  },
  {
    id: 185,
    question: 'Quel est le nom d’un des principaux massifs montagneux d’Haïti ?',
    options: ['Le Massif de la Selle', 'Le Massif Central', 'Les Alpes', 'La Cordillère des Andes'],
    correctAnswer: 0,
  },
  {
    id: 186,
    question: 'Quel est le nom du plus haut sommet du monde ?',
    options: ['Le Kilimandjaro', 'L’Everest', 'Le mont Blanc', 'L’Aconcagua'],
    correctAnswer: 1,
  },
  {
    id: 187,
    question: 'Comment appelle-t-on la science qui étudie les fossiles ?',
    options: ['La géochimie', 'La paléontologie', 'La minéralogie', 'La sismologie'],
    correctAnswer: 1,
  },
  {
    id: 188,
    question: 'Comment appelle-t-on la formation de montagnes par le plissement de la croûte terrestre ?',
    options: ['La subduction', 'L’orogenèse', 'L’érosion', 'La sédimentation'],
    correctAnswer: 1,
  },
  {
    id: 189,
    question: 'Quel gaz est principalement produit lors de la combustion complète du carbone ?',
    options: ['Monoxyde de carbone', 'Dioxyde de carbone', 'Méthane', 'Azote'],
    correctAnswer: 1,
  },
  {
    id: 190,
    question: 'Comment appelle-t-on la limite entre deux plaques tectoniques qui se rapprochent l’une de l’autre ?',
    options: ['Une limite divergente', 'Une limite convergente', 'Une faille transformante', 'Une dorsale'],
    correctAnswer: 1,
  },
  {
    id: 191,
    question: 'Quel type de roche se forme à partir de cendres volcaniques compactées ?',
    options: ['Le calcaire', 'Le tuf volcanique', 'Le grès', 'Le marbre'],
    correctAnswer: 1,
  },
  {
    id: 192,
    question: 'Comment appelle-t-on l’étude des séismes passés à partir de traces géologiques ?',
    options: ['La sismologie moderne uniquement', 'La paléosismologie', 'La stratigraphie', 'La géodésie'],
    correctAnswer: 1,
  },
  {
    id: 193,
    question: 'Comment appelle-t-on l’ensemble des caractères héréditaires transmis par les parents ?',
    options: ['Le métabolisme', 'Le patrimoine génétique', 'Le système immunitaire', 'Le cycle cellulaire'],
    correctAnswer: 1,
  },
  {
    id: 194,
    question: 'Sur quel continent se situe géographiquement Haïti ?',
    options: ['L’Afrique', 'L’Amérique (Caraïbes)', 'L’Asie', 'L’Europe'],
    correctAnswer: 1,
  },
  {
    id: 195,
    question: 'Comment appelle-t-on le mouvement de deux plaques tectoniques qui s’éloignent l’une de l’autre ?',
    options: ['La subduction', 'La divergence', 'La collision', 'La transformation'],
    correctAnswer: 1,
  },
  {
    id: 196,
    question: 'Comment appelle-t-on une petite chaîne de montagnes ou de collines ?',
    options: ['Un plateau', 'Un massif', 'Une plaine', 'Un bassin'],
    correctAnswer: 1,
  },
  {
    id: 197,
    question: 'Comment appelle-t-on le mouvement lent et continu des plaques tectoniques ?',
    options: ['La subduction uniquement', 'La tectonique des plaques', 'L’érosion', 'La sédimentation'],
    correctAnswer: 1,
  },
  {
    id: 198,
    question: 'Comment appelle-t-on la science qui étudie la répartition des terres et des mers à la surface du globe ?',
    options: ['La géologie', 'La géographie physique', 'La sismologie', 'La météorologie'],
    correctAnswer: 1,
  },
  {
    id: 199,
    question: 'Quel est le nom de la limite où une plaque océanique plonge sous une autre plaque ?',
    options: ['Une dorsale', 'Une zone de subduction', 'Une faille transformante', 'Un rift'],
    correctAnswer: 1,
  },
  {
    id: 200,
    question: 'Comment appelle-t-on l’instabilité du sol provoquée par la présence excessive d’eau lors d’un séisme ?',
    options: ['La cristallisation', 'La liquéfaction du sol', 'La solidification', 'L’évaporation'],
    correctAnswer: 1,
  },
  {
    id: 201,
    question: 'Quel est le rôle principal des poumons ?',
    options: ['Filtrer le sang', 'Échanger l’oxygène et le dioxyde de carbone', 'Produire des hormones', 'Digérer les graisses'],
    correctAnswer: 1,
  },
  {
    id: 202,
    question: 'Quel est le symbole chimique du magnésium ?',
    options: ['Mn', 'Mg', 'M', 'Mgs'],
    correctAnswer: 1,
  },
  {
    id: 203,
    question: 'Comment appelle-t-on la couche gazeuse qui entoure la Terre ?',
    options: ['L’hydrosphère', 'L’atmosphère', 'La lithosphère', 'La biosphère'],
    correctAnswer: 1,
  },
  {
    id: 204,
    question: 'Quelle est la charge électrique globale d’un atome neutre ?',
    options: ['Positive', 'Nulle', 'Négative', 'Variable'],
    correctAnswer: 1,
  },
  {
    id: 205,
    question: 'Quel type de roche se forme par cristallisation lente du magma en profondeur ?',
    options: ['Roche volcanique', 'Roche plutonique', 'Roche sédimentaire', 'Roche calcaire'],
    correctAnswer: 1,
  },
  {
    id: 206,
    question: 'Quel est le symbole chimique du plomb ?',
    options: ['Pl', 'Pb', 'P', 'Po'],
    correctAnswer: 1,
  },
  {
    id: 207,
    question: 'Quel est le principal gaz responsable de l’effet de serre naturel de la Terre ?',
    options: ['L’oxygène', 'Le dioxyde de carbone', 'L’azote', 'L’hydrogène'],
    correctAnswer: 1,
  },
  {
    id: 208,
    question: 'Comment appelle-t-on deux atomes du même élément ayant un nombre différent de neutrons ?',
    options: ['Des isomères', 'Des isotopes', 'Des ions', 'Des allotropes'],
    correctAnswer: 1,
  },
  {
    id: 209,
    question: 'Comment appelle-t-on la maladie causée par une carence en fer dans le sang ?',
    options: ['Le diabète', 'L’anémie', 'L’asthme', 'La rougeole'],
    correctAnswer: 1,
  },
  {
    id: 210,
    question: 'Quel est le symbole chimique de l’hélium ?',
    options: ['H', 'He', 'Hl', 'Hu'],
    correctAnswer: 1,
  },
  {
    id: 211,
    question: 'Comment appelle-t-on le cycle de transformation continue de l’eau sur Terre ?',
    options: ['Le cycle du carbone', 'Le cycle de l’eau', 'Le cycle de l’azote', 'Le cycle des roches'],
    correctAnswer: 1,
  },
  {
    id: 212,
    question: 'Comment appelle-t-on la quantité de chaleur nécessaire pour élever la température d’une substance ?',
    options: ['L’énergie cinétique', 'La chaleur spécifique', 'La pression', 'La densité'],
    correctAnswer: 1,
  },
  {
    id: 213,
    question: 'Dans quel état de la matière les particules sont-elles les plus rapprochées ?',
    options: ['Gazeux', 'Liquide', 'Solide', 'Plasma'],
    correctAnswer: 2,
  },
  {
    id: 214,
    question: 'Quel est le symbole chimique du sodium ?',
    options: ['S', 'Na', 'So', 'Sd'],
    correctAnswer: 1,
  },
  {
    id: 215,
    question: 'Quel type de sol est particulièrement fertile grâce aux cendres volcaniques ?',
    options: ['Le sol sableux', 'Le sol volcanique', 'Le sol argileux uniquement', 'Le sol calcaire'],
    correctAnswer: 1,
  },
  {
    id: 216,
    question: 'Comment appelle-t-on la vitesse à laquelle une réaction chimique se produit ?',
    options: ['L’équilibre chimique', 'La vitesse de réaction', 'La masse molaire', 'La concentration'],
    correctAnswer: 1,
  },
  {
    id: 217,
    question: 'Comment appelle-t-on la science qui étudie les volcans ?',
    options: ['La sismologie', 'La volcanologie', 'La météorologie', 'La minéralogie'],
    correctAnswer: 1,
  },
  {
    id: 218,
    question: 'Quel est le symbole chimique du fer ?',
    options: ['F', 'Fe', 'Fr', 'Fi'],
    correctAnswer: 1,
  },
  {
    id: 219,
    question: 'Comment appelle-t-on la science qui étudie les glaciers et les zones englacées ?',
    options: ['La climatologie', 'La glaciologie', 'L’océanographie', 'La météorologie'],
    correctAnswer: 1,
  },
  {
    id: 220,
    question: 'Comment appelle-t-on un mélange dans lequel les composants restent visibles séparément ?',
    options: ['Un mélange homogène', 'Un mélange hétérogène', 'Une solution', 'Un composé'],
    correctAnswer: 1,
  },
  {
    id: 221,
    question: 'Quel est le nom de la cellule reproductrice mâle chez l’humain ?',
    options: ['L’ovule', 'Le spermatozoïde', 'Le zygote', 'L’embryon'],
    correctAnswer: 1,
  },
  {
    id: 222,
    question: 'Quel est le symbole chimique du silicium ?',
    options: ['Sl', 'Si', 'S', 'Sc'],
    correctAnswer: 1,
  },
  {
    id: 223,
    question: 'Quel est le nom du phénomène par lequel l’eau s’infiltre lentement dans le sol ?',
    options: ['Le ruissellement', 'L’infiltration', 'L’évaporation', 'La condensation'],
    correctAnswer: 1,
  },
  {
    id: 224,
    question: 'Comment appelle-t-on l’unité qui exprime la quantité de matière en chimie ?',
    options: ['Le gramme', 'La mole', 'Le litre', 'Le kelvin'],
    correctAnswer: 1,
  },
  {
    id: 225,
    question: 'Quel élément chimique est le plus abondant dans la croûte terrestre ?',
    options: ['Le fer', 'L’oxygène', 'Le carbone', 'L’azote'],
    correctAnswer: 1,
  },
  {
    id: 226,
    question: 'Quel est le symbole chimique du phosphore ?',
    options: ['Ph', 'P', 'Po', 'Pf'],
    correctAnswer: 1,
  },
  {
    id: 227,
    question: 'Comment appelle-t-on une grande étendue de terre entourée d’eau, plus petite qu’un continent ?',
    options: ['Une péninsule', 'Une île', 'Un isthme', 'Un archipel uniquement'],
    correctAnswer: 1,
  },
  {
    id: 228,
    question: 'Comment appelle-t-on une réaction chimique qui absorbe de la chaleur ?',
    options: ['Une réaction exothermique', 'Une réaction endothermique', 'Une réaction spontanée', 'Une réaction réversible'],
    correctAnswer: 1,
  },
  {
    id: 229,
    question: 'Comment appelle-t-on l’étude des relations entre les êtres vivants et leur milieu ?',
    options: ['La génétique', 'L’écologie', 'L’anatomie', 'La physiologie'],
    correctAnswer: 1,
  },
  {
    id: 230,
    question: 'Quel est le symbole chimique du manganèse ?',
    options: ['Mg', 'Mn', 'Ma', 'Mns'],
    correctAnswer: 1,
  },
  {
    id: 231,
    question: 'Quel type de roche résulte de la solidification rapide de la lave à la surface ?',
    options: ['Une roche plutonique', 'Une roche volcanique', 'Une roche sédimentaire', 'Une roche métamorphique'],
    correctAnswer: 1,
  },
  {
    id: 232,
    question: 'Comment appelle-t-on la transformation d’un solide en liquide sous l’effet de la chaleur ?',
    options: ['La solidification', 'La fusion', 'La sublimation', 'La condensation'],
    correctAnswer: 1,
  },
  {
    id: 233,
    question: 'Comment appelle-t-on la zone où un séisme se produit habituellement à la limite de deux plaques ?',
    options: ['Une dorsale océanique uniquement', 'Une zone de faille', 'Un cratère', 'Un bassin sédimentaire'],
    correctAnswer: 1,
  },
  {
    id: 234,
    question: 'Quel est le symbole chimique de l’aluminium ?',
    options: ['Al', 'Am', 'Au', 'A'],
    correctAnswer: 0,
  },
  {
    id: 235,
    question: 'Quel phénomène géologique cause la formation de vallées en forme de U ?',
    options: ['L’érosion fluviale', 'L’érosion glaciaire', 'La sédimentation marine', 'La tectonique des plaques'],
    correctAnswer: 1,
  },
  {
    id: 236,
    question: 'Comment appelle-t-on un composé formé par la combinaison d’un métal et d’un non-métal, comme le sel ?',
    options: ['Un composé covalent', 'Un composé ionique', 'Un alliage', 'Un polymère'],
    correctAnswer: 1,
  },
  {
    id: 237,
    question: 'Comment appelle-t-on le tableau qui classe les éléments chimiques ?',
    options: ['Le tableau atomique', 'Le tableau périodique', 'Le tableau moléculaire', 'Le tableau isotopique'],
    correctAnswer: 1,
  },
  {
    id: 238,
    question: 'Quel est le symbole chimique du néon ?',
    options: ['N', 'Ne', 'No', 'Nn'],
    correctAnswer: 1,
  },
  {
    id: 239,
    question: 'Quel est le nom de la plus grande île des Antilles, partagée entre Haïti et la République dominicaine ?',
    options: ['Cuba', 'Hispaniola', 'la Jamaïque', 'Porto Rico'],
    correctAnswer: 1,
  },
  {
    id: 240,
    question: 'Quelle est l’unité de mesure de la quantité de matière en chimie ?',
    options: ['Le gramme', 'La mole', 'Le litre', 'Le newton'],
    correctAnswer: 1,
  },
  {
    id: 241,
    question: 'Quel est le symbole chimique de l’azote ?',
    options: ['Az', 'N', 'A', 'Nt'],
    correctAnswer: 1,
  },
  {
    id: 242,
    question: 'Quel est le symbole chimique du titane ?',
    options: ['Ta', 'Ti', 'Tn', 'Tt'],
    correctAnswer: 1,
  },
  {
    id: 243,
    question: 'Comment appelle-t-on une substance formée de deux éléments chimiques ou plus liés chimiquement ?',
    options: ['Un mélange', 'Un composé', 'Un isotope', 'Un ion'],
    correctAnswer: 1,
  },
  {
    id: 244,
    question: 'Comment appelle-t-on la capacité d’une substance à se dissoudre dans un solvant ?',
    options: ['La densité', 'La solubilité', 'La viscosité', 'La conductivité'],
    correctAnswer: 1,
  },
  {
    id: 245,
    question: 'Quel est le symbole chimique de l’or ?',
    options: ['Or', 'Au', 'Ag', 'O'],
    correctAnswer: 1,
  },
  {
    id: 246,
    question: 'Quel est le symbole chimique du nickel ?',
    options: ['Nk', 'Ni', 'Nc', 'Ne'],
    correctAnswer: 1,
  },
  {
    id: 247,
    question: 'Comment appelle-t-on la plus petite particule d’un élément qui garde ses propriétés chimiques ?',
    options: ['La molécule', 'L’atome', 'L’ion', 'Le composé'],
    correctAnswer: 1,
  },
  {
    id: 248,
    question: 'Comment appelle-t-on le résidu solide qui se dépose au fond d’une solution après une réaction ?',
    options: ['Un solvant', 'Un précipité', 'Un catalyseur', 'Un indicateur'],
    correctAnswer: 1,
  },
  {
    id: 249,
    question: 'Quel est le nom de la particule chargée négativement dans un atome ?',
    options: ['Le proton', 'L’électron', 'Le neutron', 'Le noyau'],
    correctAnswer: 1,
  },
  {
    id: 250,
    question: 'Quel est le symbole chimique de l’iode ?',
    options: ['Io', 'I', 'Id', 'In'],
    correctAnswer: 1,
  },
  {
    id: 251,
    question: 'Comment appelle-t-on la particule sans charge électrique dans le noyau d’un atome ?',
    options: ['Le proton', 'Le neutron', 'L’électron', 'L’ion'],
    correctAnswer: 1,
  },
  {
    id: 252,
    question: 'Comment appelle-t-on l’énergie minimale nécessaire pour démarrer une réaction chimique ?',
    options: ['L’énergie potentielle', 'L’énergie d’activation', 'L’énergie cinétique', 'L’énergie thermique'],
    correctAnswer: 1,
  },
  {
    id: 253,
    question: 'Quel est le symbole chimique de l’hydrogène ?',
    options: ['He', 'H', 'Hy', 'Hg'],
    correctAnswer: 1,
  },
  {
    id: 254,
    question: 'Quel est le symbole chimique du brome ?',
    options: ['Bo', 'Br', 'B', 'Bm'],
    correctAnswer: 1,
  },
  {
    id: 255,
    question: 'Comment appelle-t-on une réaction chimique qui libère de la chaleur ?',
    options: ['Une réaction endothermique', 'Une réaction exothermique', 'Une réaction neutre', 'Une réaction réversible'],
    correctAnswer: 1,
  },
  {
    id: 256,
    question: 'Comment appelle-t-on la couche externe d’un atome où se trouvent les électrons impliqués dans les liaisons ?',
    options: ['Le noyau', 'La couche de valence', 'Le nucléon', 'L’orbite interne'],
    correctAnswer: 1,
  },
  {
    id: 257,
    question: 'Quel est le symbole chimique de l’argent ?',
    options: ['Ar', 'Ag', 'Au', 'A'],
    correctAnswer: 1,
  },
  {
    id: 258,
    question: 'Quel est le symbole chimique du baryum ?',
    options: ['Ba', 'By', 'B', 'Bu'],
    correctAnswer: 0,
  },
  {
    id: 259,
    question: 'Comment appelle-t-on une substance qui ne peut pas être décomposée en substances plus simples ?',
    options: ['Un composé', 'Un élément chimique', 'Un mélange', 'Une solution'],
    correctAnswer: 1,
  },
  {
    id: 260,
    question: 'Quel acide fort est couramment utilisé dans les batteries de voiture ?',
    options: ['L’acide acétique', 'L’acide sulfurique', 'L’acide citrique', 'L’acide carbonique'],
    correctAnswer: 1,
  },
  {
    id: 261,
    question: 'Quel est le pH approximatif d’une solution acide ?',
    options: ['Supérieur à 7', 'Inférieur à 7', 'Égal à 7', 'Égal à 14'],
    correctAnswer: 1,
  },
  {
    id: 262,
    question: 'Quel est le symbole chimique de l’étain ?',
    options: ['Et', 'Sn', 'St', 'Ta'],
    correctAnswer: 1,
  },
  {
    id: 263,
    question: 'Comment appelle-t-on le passage direct d’un solide à un gaz sans passer par l’état liquide ?',
    options: ['La condensation', 'La sublimation', 'La fusion', 'La vaporisation'],
    correctAnswer: 1,
  },
  {
    id: 264,
    question: 'Comment appelle-t-on la transformation d’un liquide en solide par refroidissement ?',
    options: ['La fusion', 'La solidification', 'La vaporisation', 'La sublimation'],
    correctAnswer: 1,
  },
  {
    id: 265,
    question: 'Quel est le symbole chimique du chlore ?',
    options: ['Ch', 'Cl', 'Co', 'C'],
    correctAnswer: 1,
  },
  {
    id: 266,
    question: 'Quel est le symbole chimique du platine ?',
    options: ['Pt', 'Pl', 'Pn', 'P'],
    correctAnswer: 0,
  },
  {
    id: 267,
    question: 'Comment appelle-t-on un mélange homogène de deux substances, comme le sel dans l’eau ?',
    options: ['Une suspension', 'Une solution', 'Un colloïde', 'Un précipité'],
    correctAnswer: 1,
  },
  {
    id: 268,
    question: 'Comment appelle-t-on une substance qui empêche ou ralentit une réaction chimique ?',
    options: ['Un catalyseur', 'Un inhibiteur', 'Un réactif', 'Un précipité'],
    correctAnswer: 1,
  },
  {
    id: 269,
    question: 'Quel est le nom de la force qui maintient les atomes liés dans une molécule ?',
    options: ['La gravité', 'Une liaison chimique', 'Le magnétisme', 'La friction'],
    correctAnswer: 1,
  },
  {
    id: 270,
    question: 'Quel est le symbole chimique du mercure ?',
    options: ['Me', 'Hg', 'Mr', 'M'],
    correctAnswer: 1,
  },
  {
    id: 271,
    question: 'Comment appelle-t-on une substance qui change de couleur selon le pH d’une solution ?',
    options: ['Un solvant', 'Un indicateur coloré', 'Un catalyseur', 'Un précipité'],
    correctAnswer: 1,
  },
  {
    id: 272,
    question: 'Comment appelle-t-on la propriété d’une substance à conduire l’électricité ?',
    options: ['La solubilité', 'La conductivité électrique', 'La densité', 'La viscosité'],
    correctAnswer: 1,
  },
  {
    id: 273,
    question: 'Quel est le symbole chimique du calcium ?',
    options: ['Cl', 'Ca', 'C', 'Cd'],
    correctAnswer: 1,
  },
  {
    id: 274,
    question: 'Quel gaz incolore et inodore, dangereux, est produit par une combustion incomplète ?',
    options: ['Le dioxyde de carbone', 'Le monoxyde de carbone', 'Le méthane', 'L’azote'],
    correctAnswer: 1,
  },
  {
    id: 275,
    question: 'Quel gaz est généralement libéré lors de la réaction entre un acide et un métal ?',
    options: ['L’oxygène', 'L’hydrogène', 'L’azote', 'Le dioxyde de carbone'],
    correctAnswer: 1,
  },
  {
    id: 276,
    question: 'Comment appelle-t-on le processus par lequel une substance se répand uniformément dans une autre ?',
    options: ['L’osmose uniquement', 'La diffusion', 'La filtration', 'La décantation'],
    correctAnswer: 1,
  },
  {
    id: 277,
    question: 'Comment appelle-t-on une transformation qui produit une ou plusieurs nouvelles substances ?',
    options: ['Un changement d’état', 'Une réaction chimique', 'Une dilution', 'Une filtration'],
    correctAnswer: 1,
  },
  {
    id: 278,
    question: 'Quel est le symbole chimique du lithium ?',
    options: ['Li', 'Lt', 'L', 'Lm'],
    correctAnswer: 0,
  },
  {
    id: 279,
    question: 'Quel est le symbole chimique du potassium ?',
    options: ['P', 'K', 'Po', 'Pt'],
    correctAnswer: 1,
  },
  {
    id: 280,
    question: 'Comment appelle-t-on la masse d’une mole d’une substance ?',
    options: ['La masse volumique', 'La masse molaire', 'La densité', 'La masse atomique relative uniquement'],
    correctAnswer: 1,
  },
  {
    id: 281,
    question: 'Comment appelle-t-on un atome ou une molécule qui a perdu ou gagné des électrons ?',
    options: ['Un isotope', 'Un ion', 'Un composé', 'Un radical'],
    correctAnswer: 1,
  },
  {
    id: 282,
    question: 'Quel est le composant de l’air respiré présent en plus grande proportion ?',
    options: ['L’oxygène', 'L’azote', 'Le dioxyde de carbone', 'L’argon'],
    correctAnswer: 1,
  },
  {
    id: 283,
    question: 'Quel est le principal composant du gaz naturel utilisé comme combustible ?',
    options: ['L’éthanol', 'Le méthane', 'Le propane uniquement', 'Le butane uniquement'],
    correctAnswer: 1,
  },
  {
    id: 284,
    question: 'Comment appelle-t-on un composé qui libère des ions hydrogène (H+) en solution ?',
    options: ['Une base', 'Un acide', 'Un sel', 'Un solvant'],
    correctAnswer: 1,
  },
  {
    id: 285,
    question: 'Comment appelle-t-on la transformation d’un gaz en liquide ?',
    options: ['La sublimation', 'La condensation', 'La fusion', 'La solidification'],
    correctAnswer: 1,
  },
  {
    id: 286,
    question: 'Quel est le symbole chimique du bore ?',
    options: ['Bo', 'B', 'Br', 'Bm'],
    correctAnswer: 1,
  },
  {
    id: 287,
    question: 'Quel est le symbole chimique du cuivre ?',
    options: ['Co', 'Cu', 'Cr', 'C'],
    correctAnswer: 1,
  },
  {
    id: 288,
    question: 'Comment appelle-t-on un composé qui libère des ions hydroxyde (OH-) en solution ?',
    options: ['Un acide', 'Une base', 'Un sel', 'Un oxyde'],
    correctAnswer: 1,
  },
  {
    id: 289,
    question: 'Comment appelle-t-on une solution dont le pH est supérieur à 7 ?',
    options: ['Une solution acide', 'Une solution basique', 'Une solution neutre', 'Une solution saturée'],
    correctAnswer: 1,
  },
  {
    id: 290,
    question: 'Quel est le symbole chimique du chrome ?',
    options: ['Ch', 'Cr', 'C', 'Co'],
    correctAnswer: 1,
  },
  {
    id: 291,
    question: 'Comment appelle-t-on le processus par lequel les métaux se dégradent au contact de l’air et de l’humidité ?',
    options: ['La cristallisation', 'La corrosion', 'La sublimation', 'La combustion'],
    correctAnswer: 1,
  },
  {
    id: 292,
    question: 'Comment appelle-t-on la représentation symbolique d’une réaction chimique avec des formules ?',
    options: ['Un diagramme', 'Une équation chimique', 'Un tableau périodique', 'Un schéma moléculaire'],
    correctAnswer: 1,
  },
  {
    id: 293,
    question: 'Comment appelle-t-on l’étude de la composition et des transformations de la matière ?',
    options: ['La physique', 'La chimie', 'La biologie', 'La géologie'],
    correctAnswer: 1,
  },
  {
    id: 294,
    question: 'Quel est le symbole chimique du cobalt ?',
    options: ['Cb', 'Co', 'Ct', 'C'],
    correctAnswer: 1,
  },
  {
    id: 295,
    question: 'Quel est le symbole chimique du zinc ?',
    options: ['Zc', 'Zn', 'Z', 'Zi'],
    correctAnswer: 1,
  },
  {
    id: 296,
    question: 'Comment appelle-t-on un matériau qui ne conduit pas l’électricité ?',
    options: ['Un conducteur', 'Un isolant', 'Un semi-conducteur', 'Un alliage'],
    correctAnswer: 1,
  },
  {
    id: 297,
    question: 'Comment appelle-t-on la plus petite unité formée par l’union de plusieurs atomes ?',
    options: ['Un ion', 'Une molécule', 'Un élément', 'Un isotope'],
    correctAnswer: 1,
  },
  {
    id: 298,
    question: 'Quel est le symbole chimique du xénon ?',
    options: ['Xn', 'Xe', 'X', 'Xo'],
    correctAnswer: 1,
  },
  {
    id: 299,
    question: 'Quel est le symbole chimique du soufre ?',
    options: ['So', 'S', 'Su', 'Sf'],
    correctAnswer: 1,
  },
  {
    id: 300,
    question: 'Comment appelle-t-on la branche de la chimie qui étudie les composés du carbone ?',
    options: ['La chimie minérale', 'La chimie organique', 'La chimie nucléaire', 'La chimie analytique'],
    correctAnswer: 1,
  },
];
